# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.script_execute_response import ScriptExecuteResponse
from ..types.script_ref_request import ScriptRefRequest
from ..types.script_response import ScriptResponse
from .raw_client import AsyncRawScriptsClient, RawScriptsClient
from .types.list_scripts_response import ListScriptsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ScriptsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawScriptsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawScriptsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawScriptsClient
        """
        return self._raw_client

    def execute_script(
        self,
        *,
        script_ref: ScriptRefRequest,
        idempotency_key: typing.Optional[str] = None,
        input: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScriptExecuteResponse:
        """
        Runs a script you previously pushed to `POST /v1/scripts`, under your own credential, and returns what it returned. Every write the script makes is buffered and committed as ONE transaction after the script finishes: either all of them land or none do, and the response is sent only after they have committed — so everything in `result` is committed state or the script's own computation over it. On any failure the body is the standard error envelope and nothing the script staged is committed: its rows are written only when the transaction commits, and a document body or a large payload is DECIDED at that point and WRITTEN to storage only after the commit, so an aborted execution leaves nothing behind. The one residual sits after a successful commit, outside this response: if storing a body fails then, the row exists and the body does not until the platform's repair lands — so a `200` guarantees the rows, and a document's text should be read before it is relied on.

        **Permission.** Requires the `scripts:x` scope — the permission to *execute* — separate from the `scripts:c` permission to push scripts. Bare `scripts:x` grants every script in the context; `scripts:x:<name>` grants exactly that script name, every version of it. Execution discloses no source, so `scripts:r` is not needed. Inside the script, every read and write is enforced by your credential's data scopes exactly as the equivalent REST call would be — `scripts:x` alone can read and write nothing.

        **Input.** Your script sees `input.event` (the literal `"execute"`), `input.userId` (your credential's user id, or null), and `input.params` (the `input` object you sent, verbatim). That is the same `input` grammar a trigger rule uses, so one script can serve both by branching on `input.event`. `params` is not validated — a script that needs a shape checks for it and throws; the script's `declaredInputContract` is documentation for readers and is not enforced.

        **Budget.** Seconds of useful work: the script has 15 s of wall clock (never more than 16) and a bounded number of statements and host calls; a runaway script is stopped early with `RESOURCE_LIMIT_EXCEEDED`. The transaction is bounded by the number of underlying storage rows it writes — 100 rows after merging — rather than by the number of entities: creating a folder costs 3 rows; creating a plain text document or a record costs 1 row plus one per range-indexed lookup field plus one per `reference` field. So "create a folder and file N documents" holds up to 97 plain documents, 48 with one range field or one reference, 32 with both; if a script exceeds the limit the error says so (`WRITE_BUFFER_CAP_EXCEEDED`, with `total` and `limit`) and nothing is committed. This request takes the write-path limits (burst, credit ceiling, principal quota) once, before the script runs — there is no free-read allowance here, so an account over its credit ceiling is refused even for a read-only script. Reads the script performs are metered as reads, writes as writes, and execution time beyond what those operations include is charged as script execution time (see `GET /v1/usage`).

        **Reads inside the script.** A `get` sees the script's own staged writes. A list, query or lookup never shows a row the script has deleted, shows a row it re-saved with the updated content, and does not show a row it created — you hold that row's id from `create()`.

        **Retries.** Send an optional `Idempotency-Key` header (1–128 characters of letters, digits, `.`, `_`, `:` or `-`) to make a retry safe: a request repeated under the same key within 24 hours receives the same response as the first attempt without executing again — when that first attempt SUCCEEDED (a duplicate still in flight is refused with `409 IDEMPOTENCY_IN_PROGRESS`; the same key on a different request is refused with `422 IDEMPOTENCY_KEY_REUSED`). A first attempt that FAILED with any other status is not remembered: the same key is free to try again, so a retry after a `400` or a `429` executes. If an execution's outcome cannot be determined — the script did not finish inside the budget while its writes may have committed — the response is `500 EXECUTION_OUTCOME_UNKNOWN` carrying `execution.id`, and a keyed retry receives that same answer: inspect what the script would have written, then use a NEW key for a new attempt. When a key is present the serialised `result` is capped at 16 KB instead of 256 KB. Without a key, a lost response cannot be distinguished from a failed one; re-read before retrying.

        Parameters
        ----------
        script_ref : ScriptRefRequest

        idempotency_key : typing.Optional[str]
            Optional. 1–128 characters of letters, digits, `.`, `_`, `:` or `-`. A request repeated under the same key within 24 hours, by the same credential, receives the first attempt's response without executing again — when that attempt succeeded or ended `EXECUTION_OUTCOME_UNKNOWN`; a failed attempt is not remembered. The body is compared byte for byte, so the same key with a differently formatted body is a different request (`422`). With a key present the serialised `result` is capped at 16 KB.

        input : typing.Optional[typing.Dict[str, typing.Any]]
            A free-form JSON object your script receives as `input.params`. The platform does not validate or interpret it — a script that needs a shape checks for it and throws, which reaches you as a `400` carrying the script's own message. The script's `declaredInputContract` describes this object for readers; it is not enforced. Sized by the request body limit (256 KB for this endpoint). Omitting it is the same as `{}`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScriptExecuteResponse
            The script finished and its writes committed.

        Examples
        --------
        from vectros import ScriptRefRequest, VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.scripts.execute_script(
            idempotency_key="order-8412-attempt",
            script_ref=ScriptRefRequest(
                name="notify-assignee",
                version="3",
            ),
        )
        """
        _response = self._raw_client.execute_script(
            script_ref=script_ref, idempotency_key=idempotency_key, input=input, request_options=request_options
        )
        return _response.data

    def list_scripts(
        self,
        *,
        name: typing.Optional[str] = None,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        include_source: typing.Optional[bool] = None,
        latest: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListScriptsResponse:
        """
        Returns a paginated list of your scripts. Pass `name` to list every version of one script name (oldest first); omit it for a flat list across every name in your account (newest first). Results are returned as a `{data, nextCursor}` envelope — pass `nextCursor` as `startFrom` to fetch the next page. Requires the `scripts:r` scope. **Each row's `source` is omitted by default** (`sourceOmitted: true`) — scripts are immutable per version, so a name's version history can otherwise carry every version's complete source in one response. Pass `?includeSource=true` to get it back inline, or fetch one version's full source with a by-id GET. **`?name=<n>&latest=true`** answers "what is the current version of this name" in one bounded call — a single `ScriptResponse` object (not a page), instead of draining every page of the name's version history to find the newest yourself.

        Parameters
        ----------
        name : typing.Optional[str]
            List every version of this script name (oldest first), instead of a flat cross-name list. Required when `latest=true`.

        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` returned by the previous page to fetch the next page; omit it for the first page. The cursor is **opaque** — echo it back unchanged. Ignored when `latest=true`.

        limit : typing.Optional[int]
            Maximum number of scripts to return per page. Must be between 1 and 100; defaults to 20. Ignored when `latest=true`.

        include_source : typing.Optional[bool]
            Include each row's full `source` inline instead of the default omitted projection. Costs the same per-row weight a by-id GET pays; at `limit=100` on large scripts this can approach the response-payload ceiling (the reason the default changed). Defaults to false.

        latest : typing.Optional[bool]
            Instead of a page, return a single `ScriptResponse`: the current newest version of `name` (required alongside this). One bounded read (`GET`-by-id-equivalent cost) instead of draining every page of the name's version history to compute the max version yourself. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListScriptsResponse
            Either a page of script versions (the `{data, nextCursor}` envelope; `nextCursor` is null when there are no more pages, and each row omits `source` unless `?includeSource=true` was passed), or — when `?latest=true` was passed alongside `name` — a single script version object, the newest of that name. Distinguish the two by shape: the page envelope has a top-level `data` array, the single-object form does not.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.scripts.list_scripts(
            name="notify-assignee",
            start_from="b3BhcXVlLWN1cnNvci1mcm9tLXRoZS1wcmV2aW91cy1wYWdl",
        )
        """
        _response = self._raw_client.list_scripts(
            name=name,
            start_from=start_from,
            limit=limit,
            include_source=include_source,
            latest=latest,
            request_options=request_options,
        )
        return _response.data

    def create_script(
        self,
        *,
        name: str,
        source: str,
        declared_input_contract: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScriptResponse:
        """
        Stores a new version of a script object. Every POST creates a genuinely new version — this is NOT idempotent-by-name: pushing `name` again always creates a new row with `scriptVersion` auto-incremented (the first version pushed for a name is 1). `source` is stored as-is: nothing parses or validates it at push time. A version runs when a trigger rule references it (`POST /v1/triggers`) or when `POST /v1/scripts/execute` names it. `provisionedBy` MAY BE SET ON ABSENT, NEVER CHANGED, evaluated against the CURRENT LATEST version of this `name` at push time: if the latest version has no marker recorded, this push may set any value; if the latest version already has one, an omitted value inherits it forward and a DIFFERENT value is refused — a live comparison against whichever version is newest at push time, not a value fixed for the name's whole history. Pushing onto an EXISTING name with no `provisionedBy` recorded on its current latest version additionally requires that you were the caller who pushed that latest version — a name carrying a `provisionedBy` marker is exempt from this check (proving you can supply or inherit the matching marker is itself the ownership proof there). Requires the `scripts:c` scope.

        Parameters
        ----------
        name : str
            The script's referenceable name/slug — stable across versions. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Required.

        source : str
            The script's source text, stored as-is: nothing parses or validates it at push time, so a syntax error surfaces as a `SCRIPT_ERROR` when the version first runs — from a trigger rule that references it, or from `POST /v1/scripts/execute`. Required, non-blank. Capped at 300,000 UTF-8 bytes (~300 KB) — an oversized push is rejected with a 400.

        declared_input_contract : typing.Optional[str]
            Optional free-text description of the input shape this script expects. Not validated or enforced in this release. Capped at 50,000 UTF-8 bytes (~50 KB) — an oversized value is rejected with a 400.

        provisioned_by : typing.Optional[str]
            An optional provenance marker naming the blueprint that provisions this script, so a convergent caller can tell a script it manages from one hand-authored or owned by a different blueprint. Not currently sent by `vectros bootstrap --blueprint`, which does not yet set this field for scripts. Leave it unset for a script you manage yourself. MAY BE SET ON ABSENT, NEVER CHANGED, evaluated against the CURRENT LATEST version of this `name` at push time: if the latest version has no marker recorded, this push may set any value (including onto a previously-unmarked, hand-authored name); if the latest version already has one recorded, an omitted value inherits it forward, and supplying a DIFFERENT value is refused. This compares against whichever version is newest right now, not a value fixed for the name's whole history — deleting the version(s) carrying a given marker and pushing again is unconstrained by it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScriptResponse
            A new script version was created.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.scripts.create_script(
            name="notify-assignee",
            source="export default function(input) { return { ok: true }; }",
        )
        """
        _response = self._raw_client.create_script(
            name=name,
            source=source,
            declared_input_contract=declared_input_contract,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    def get_script(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScriptResponse:
        """
        Retrieves a single script version by its ID. Requires the `scripts:r` scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScriptResponse
            The script version was found and returned.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.scripts.get_script(
            id="id",
        )
        """
        _response = self._raw_client.get_script(id, request_options=request_options)
        return _response.data

    def update_script(
        self,
        id: str,
        *,
        name: str,
        source: str,
        declared_input_contract: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Scripts are immutable per version; this endpoint always returns a 400 regardless of scope or credential — push a new version via `POST /v1/scripts` instead.

        Parameters
        ----------
        id : str

        name : str
            The script's referenceable name/slug — stable across versions. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Required.

        source : str
            The script's source text, stored as-is: nothing parses or validates it at push time, so a syntax error surfaces as a `SCRIPT_ERROR` when the version first runs — from a trigger rule that references it, or from `POST /v1/scripts/execute`. Required, non-blank. Capped at 300,000 UTF-8 bytes (~300 KB) — an oversized push is rejected with a 400.

        declared_input_contract : typing.Optional[str]
            Optional free-text description of the input shape this script expects. Not validated or enforced in this release. Capped at 50,000 UTF-8 bytes (~50 KB) — an oversized value is rejected with a 400.

        provisioned_by : typing.Optional[str]
            An optional provenance marker naming the blueprint that provisions this script, so a convergent caller can tell a script it manages from one hand-authored or owned by a different blueprint. Not currently sent by `vectros bootstrap --blueprint`, which does not yet set this field for scripts. Leave it unset for a script you manage yourself. MAY BE SET ON ABSENT, NEVER CHANGED, evaluated against the CURRENT LATEST version of this `name` at push time: if the latest version has no marker recorded, this push may set any value (including onto a previously-unmarked, hand-authored name); if the latest version already has one recorded, an omitted value inherits it forward, and supplying a DIFFERENT value is refused. This compares against whichever version is newest right now, not a value fixed for the name's whole history — deleting the version(s) carrying a given marker and pushing again is unconstrained by it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.scripts.update_script(
            id="id",
            name="notify-assignee",
            source="export default function(input) { return { ok: true }; }",
        )
        """
        _response = self._raw_client.update_script(
            id,
            name=name,
            source=source,
            declared_input_contract=declared_input_contract,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    def delete_script(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes one script version by ID. Deleting one version does not affect any other version of the same name. Requires the `scripts:d` scope. Refused with 409 if a live trigger rule still references this version — either directly (a pinned `scriptRef`), or via `"latest"` when this IS the newest version of its name. Delete or re-point those rules first.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.scripts.delete_script(
            id="id",
        )
        """
        _response = self._raw_client.delete_script(id, request_options=request_options)
        return _response.data


class AsyncScriptsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawScriptsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawScriptsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawScriptsClient
        """
        return self._raw_client

    async def execute_script(
        self,
        *,
        script_ref: ScriptRefRequest,
        idempotency_key: typing.Optional[str] = None,
        input: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScriptExecuteResponse:
        """
        Runs a script you previously pushed to `POST /v1/scripts`, under your own credential, and returns what it returned. Every write the script makes is buffered and committed as ONE transaction after the script finishes: either all of them land or none do, and the response is sent only after they have committed — so everything in `result` is committed state or the script's own computation over it. On any failure the body is the standard error envelope and nothing the script staged is committed: its rows are written only when the transaction commits, and a document body or a large payload is DECIDED at that point and WRITTEN to storage only after the commit, so an aborted execution leaves nothing behind. The one residual sits after a successful commit, outside this response: if storing a body fails then, the row exists and the body does not until the platform's repair lands — so a `200` guarantees the rows, and a document's text should be read before it is relied on.

        **Permission.** Requires the `scripts:x` scope — the permission to *execute* — separate from the `scripts:c` permission to push scripts. Bare `scripts:x` grants every script in the context; `scripts:x:<name>` grants exactly that script name, every version of it. Execution discloses no source, so `scripts:r` is not needed. Inside the script, every read and write is enforced by your credential's data scopes exactly as the equivalent REST call would be — `scripts:x` alone can read and write nothing.

        **Input.** Your script sees `input.event` (the literal `"execute"`), `input.userId` (your credential's user id, or null), and `input.params` (the `input` object you sent, verbatim). That is the same `input` grammar a trigger rule uses, so one script can serve both by branching on `input.event`. `params` is not validated — a script that needs a shape checks for it and throws; the script's `declaredInputContract` is documentation for readers and is not enforced.

        **Budget.** Seconds of useful work: the script has 15 s of wall clock (never more than 16) and a bounded number of statements and host calls; a runaway script is stopped early with `RESOURCE_LIMIT_EXCEEDED`. The transaction is bounded by the number of underlying storage rows it writes — 100 rows after merging — rather than by the number of entities: creating a folder costs 3 rows; creating a plain text document or a record costs 1 row plus one per range-indexed lookup field plus one per `reference` field. So "create a folder and file N documents" holds up to 97 plain documents, 48 with one range field or one reference, 32 with both; if a script exceeds the limit the error says so (`WRITE_BUFFER_CAP_EXCEEDED`, with `total` and `limit`) and nothing is committed. This request takes the write-path limits (burst, credit ceiling, principal quota) once, before the script runs — there is no free-read allowance here, so an account over its credit ceiling is refused even for a read-only script. Reads the script performs are metered as reads, writes as writes, and execution time beyond what those operations include is charged as script execution time (see `GET /v1/usage`).

        **Reads inside the script.** A `get` sees the script's own staged writes. A list, query or lookup never shows a row the script has deleted, shows a row it re-saved with the updated content, and does not show a row it created — you hold that row's id from `create()`.

        **Retries.** Send an optional `Idempotency-Key` header (1–128 characters of letters, digits, `.`, `_`, `:` or `-`) to make a retry safe: a request repeated under the same key within 24 hours receives the same response as the first attempt without executing again — when that first attempt SUCCEEDED (a duplicate still in flight is refused with `409 IDEMPOTENCY_IN_PROGRESS`; the same key on a different request is refused with `422 IDEMPOTENCY_KEY_REUSED`). A first attempt that FAILED with any other status is not remembered: the same key is free to try again, so a retry after a `400` or a `429` executes. If an execution's outcome cannot be determined — the script did not finish inside the budget while its writes may have committed — the response is `500 EXECUTION_OUTCOME_UNKNOWN` carrying `execution.id`, and a keyed retry receives that same answer: inspect what the script would have written, then use a NEW key for a new attempt. When a key is present the serialised `result` is capped at 16 KB instead of 256 KB. Without a key, a lost response cannot be distinguished from a failed one; re-read before retrying.

        Parameters
        ----------
        script_ref : ScriptRefRequest

        idempotency_key : typing.Optional[str]
            Optional. 1–128 characters of letters, digits, `.`, `_`, `:` or `-`. A request repeated under the same key within 24 hours, by the same credential, receives the first attempt's response without executing again — when that attempt succeeded or ended `EXECUTION_OUTCOME_UNKNOWN`; a failed attempt is not remembered. The body is compared byte for byte, so the same key with a differently formatted body is a different request (`422`). With a key present the serialised `result` is capped at 16 KB.

        input : typing.Optional[typing.Dict[str, typing.Any]]
            A free-form JSON object your script receives as `input.params`. The platform does not validate or interpret it — a script that needs a shape checks for it and throws, which reaches you as a `400` carrying the script's own message. The script's `declaredInputContract` describes this object for readers; it is not enforced. Sized by the request body limit (256 KB for this endpoint). Omitting it is the same as `{}`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScriptExecuteResponse
            The script finished and its writes committed.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi, ScriptRefRequest

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.scripts.execute_script(
                idempotency_key="order-8412-attempt",
                script_ref=ScriptRefRequest(
                    name="notify-assignee",
                    version="3",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.execute_script(
            script_ref=script_ref, idempotency_key=idempotency_key, input=input, request_options=request_options
        )
        return _response.data

    async def list_scripts(
        self,
        *,
        name: typing.Optional[str] = None,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        include_source: typing.Optional[bool] = None,
        latest: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListScriptsResponse:
        """
        Returns a paginated list of your scripts. Pass `name` to list every version of one script name (oldest first); omit it for a flat list across every name in your account (newest first). Results are returned as a `{data, nextCursor}` envelope — pass `nextCursor` as `startFrom` to fetch the next page. Requires the `scripts:r` scope. **Each row's `source` is omitted by default** (`sourceOmitted: true`) — scripts are immutable per version, so a name's version history can otherwise carry every version's complete source in one response. Pass `?includeSource=true` to get it back inline, or fetch one version's full source with a by-id GET. **`?name=<n>&latest=true`** answers "what is the current version of this name" in one bounded call — a single `ScriptResponse` object (not a page), instead of draining every page of the name's version history to find the newest yourself.

        Parameters
        ----------
        name : typing.Optional[str]
            List every version of this script name (oldest first), instead of a flat cross-name list. Required when `latest=true`.

        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` returned by the previous page to fetch the next page; omit it for the first page. The cursor is **opaque** — echo it back unchanged. Ignored when `latest=true`.

        limit : typing.Optional[int]
            Maximum number of scripts to return per page. Must be between 1 and 100; defaults to 20. Ignored when `latest=true`.

        include_source : typing.Optional[bool]
            Include each row's full `source` inline instead of the default omitted projection. Costs the same per-row weight a by-id GET pays; at `limit=100` on large scripts this can approach the response-payload ceiling (the reason the default changed). Defaults to false.

        latest : typing.Optional[bool]
            Instead of a page, return a single `ScriptResponse`: the current newest version of `name` (required alongside this). One bounded read (`GET`-by-id-equivalent cost) instead of draining every page of the name's version history to compute the max version yourself. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListScriptsResponse
            Either a page of script versions (the `{data, nextCursor}` envelope; `nextCursor` is null when there are no more pages, and each row omits `source` unless `?includeSource=true` was passed), or — when `?latest=true` was passed alongside `name` — a single script version object, the newest of that name. Distinguish the two by shape: the page envelope has a top-level `data` array, the single-object form does not.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.scripts.list_scripts(
                name="notify-assignee",
                start_from="b3BhcXVlLWN1cnNvci1mcm9tLXRoZS1wcmV2aW91cy1wYWdl",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_scripts(
            name=name,
            start_from=start_from,
            limit=limit,
            include_source=include_source,
            latest=latest,
            request_options=request_options,
        )
        return _response.data

    async def create_script(
        self,
        *,
        name: str,
        source: str,
        declared_input_contract: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScriptResponse:
        """
        Stores a new version of a script object. Every POST creates a genuinely new version — this is NOT idempotent-by-name: pushing `name` again always creates a new row with `scriptVersion` auto-incremented (the first version pushed for a name is 1). `source` is stored as-is: nothing parses or validates it at push time. A version runs when a trigger rule references it (`POST /v1/triggers`) or when `POST /v1/scripts/execute` names it. `provisionedBy` MAY BE SET ON ABSENT, NEVER CHANGED, evaluated against the CURRENT LATEST version of this `name` at push time: if the latest version has no marker recorded, this push may set any value; if the latest version already has one, an omitted value inherits it forward and a DIFFERENT value is refused — a live comparison against whichever version is newest at push time, not a value fixed for the name's whole history. Pushing onto an EXISTING name with no `provisionedBy` recorded on its current latest version additionally requires that you were the caller who pushed that latest version — a name carrying a `provisionedBy` marker is exempt from this check (proving you can supply or inherit the matching marker is itself the ownership proof there). Requires the `scripts:c` scope.

        Parameters
        ----------
        name : str
            The script's referenceable name/slug — stable across versions. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Required.

        source : str
            The script's source text, stored as-is: nothing parses or validates it at push time, so a syntax error surfaces as a `SCRIPT_ERROR` when the version first runs — from a trigger rule that references it, or from `POST /v1/scripts/execute`. Required, non-blank. Capped at 300,000 UTF-8 bytes (~300 KB) — an oversized push is rejected with a 400.

        declared_input_contract : typing.Optional[str]
            Optional free-text description of the input shape this script expects. Not validated or enforced in this release. Capped at 50,000 UTF-8 bytes (~50 KB) — an oversized value is rejected with a 400.

        provisioned_by : typing.Optional[str]
            An optional provenance marker naming the blueprint that provisions this script, so a convergent caller can tell a script it manages from one hand-authored or owned by a different blueprint. Not currently sent by `vectros bootstrap --blueprint`, which does not yet set this field for scripts. Leave it unset for a script you manage yourself. MAY BE SET ON ABSENT, NEVER CHANGED, evaluated against the CURRENT LATEST version of this `name` at push time: if the latest version has no marker recorded, this push may set any value (including onto a previously-unmarked, hand-authored name); if the latest version already has one recorded, an omitted value inherits it forward, and supplying a DIFFERENT value is refused. This compares against whichever version is newest right now, not a value fixed for the name's whole history — deleting the version(s) carrying a given marker and pushing again is unconstrained by it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScriptResponse
            A new script version was created.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.scripts.create_script(
                name="notify-assignee",
                source="export default function(input) { return { ok: true }; }",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_script(
            name=name,
            source=source,
            declared_input_contract=declared_input_contract,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    async def get_script(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScriptResponse:
        """
        Retrieves a single script version by its ID. Requires the `scripts:r` scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScriptResponse
            The script version was found and returned.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.scripts.get_script(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_script(id, request_options=request_options)
        return _response.data

    async def update_script(
        self,
        id: str,
        *,
        name: str,
        source: str,
        declared_input_contract: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Scripts are immutable per version; this endpoint always returns a 400 regardless of scope or credential — push a new version via `POST /v1/scripts` instead.

        Parameters
        ----------
        id : str

        name : str
            The script's referenceable name/slug — stable across versions. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Required.

        source : str
            The script's source text, stored as-is: nothing parses or validates it at push time, so a syntax error surfaces as a `SCRIPT_ERROR` when the version first runs — from a trigger rule that references it, or from `POST /v1/scripts/execute`. Required, non-blank. Capped at 300,000 UTF-8 bytes (~300 KB) — an oversized push is rejected with a 400.

        declared_input_contract : typing.Optional[str]
            Optional free-text description of the input shape this script expects. Not validated or enforced in this release. Capped at 50,000 UTF-8 bytes (~50 KB) — an oversized value is rejected with a 400.

        provisioned_by : typing.Optional[str]
            An optional provenance marker naming the blueprint that provisions this script, so a convergent caller can tell a script it manages from one hand-authored or owned by a different blueprint. Not currently sent by `vectros bootstrap --blueprint`, which does not yet set this field for scripts. Leave it unset for a script you manage yourself. MAY BE SET ON ABSENT, NEVER CHANGED, evaluated against the CURRENT LATEST version of this `name` at push time: if the latest version has no marker recorded, this push may set any value (including onto a previously-unmarked, hand-authored name); if the latest version already has one recorded, an omitted value inherits it forward, and supplying a DIFFERENT value is refused. This compares against whichever version is newest right now, not a value fixed for the name's whole history — deleting the version(s) carrying a given marker and pushing again is unconstrained by it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.scripts.update_script(
                id="id",
                name="notify-assignee",
                source="export default function(input) { return { ok: true }; }",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_script(
            id,
            name=name,
            source=source,
            declared_input_contract=declared_input_contract,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    async def delete_script(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes one script version by ID. Deleting one version does not affect any other version of the same name. Requires the `scripts:d` scope. Refused with 409 if a live trigger rule still references this version — either directly (a pinned `scriptRef`), or via `"latest"` when this IS the newest version of its name. Delete or re-point those rules first.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.scripts.delete_script(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_script(id, request_options=request_options)
        return _response.data
