# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..types.filter_value import FilterValue
from ..types.search_response import SearchResponse
from .types.search_request_content_types_item import SearchRequestContentTypesItem
from .types.search_request_mode import SearchRequestMode
from .types.search_request_text_mode import SearchRequestTextMode
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def content(
        self,
        *,
        query: str,
        mode: typing.Optional[SearchRequestMode] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        org_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, FilterValue]] = OMIT,
        text_mode: typing.Optional[SearchRequestTextMode] = OMIT,
        min_similarity: typing.Optional[float] = OMIT,
        min_text_relevance: typing.Optional[float] = OMIT,
        slop: typing.Optional[int] = OMIT,
        unique_documents: typing.Optional[bool] = OMIT,
        content_types: typing.Optional[typing.Sequence[SearchRequestContentTypesItem]] = OMIT,
        folder_id: typing.Optional[str] = OMIT,
        root_folder_id: typing.Optional[str] = OMIT,
        type_name: typing.Optional[str] = OMIT,
        created_after: typing.Optional[str] = OMIT,
        created_before: typing.Optional[str] = OMIT,
        require_complete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SearchResponse]:
        """
        Runs a hybrid, semantic, or text search across the content you have indexed. By default it returns both documents and records in a single unified result set; pass `contentTypes` to narrow the results (for example `["documents"]`). Each result carries a `sourceType` discriminator (`PartnerDocument` or `GenericRecord`) so you can branch on the type. Requires the `search:r` scope.

        Parameters
        ----------
        query : str
            The search query, expressed in natural language or as keywords. Required.

        mode : typing.Optional[SearchRequestMode]
            How results are ranked. HYBRID combines semantic and keyword ranking (recommended). SEMANTIC ranks by vector similarity only. TEXT ranks by keyword matching only. Defaults to HYBRID.

        limit : typing.Optional[int]
            The maximum number of results to return. Must be between 1 and 100. Defaults to 20.

        offset : typing.Optional[int]
            The number of results to skip, for pagination. Must be between 0 and 200. Defaults to 0.

        user_id : typing.Optional[str]
            Restrict results to content owned by this user — the Vectros-assigned UUID of a user in your account. Use `GET /v1/users?externalId=` to look up a user's ID from your own identifier.

        org_id : typing.Optional[str]
            Restrict results to content belonging to this organization — the Vectros-assigned UUID of an organization in your account. Use `GET /v1/orgs?externalId=` to look up an organization's ID from your own identifier.

        client_id : typing.Optional[str]
            Restrict results to content associated with this client — the Vectros-assigned UUID of a client in your account. Use `GET /v1/clients?externalId=` to look up a client's ID from your own identifier.

        filters : typing.Optional[typing.Dict[str, FilterValue]]
            Field-level filters applied to your document and record metadata. Each key is a field name, and top-level keys are AND-combined. Each value is one of: a scalar (string, number, or boolean) for an exact match; an array of scalars to match any one of them; or an operator map for ranges, negation, and membership. The supported operators are a closed set: `$eq`, `$ne`, `$gt`, `$gte`, `$lt`, `$lte` (each takes a scalar) and `$in`, `$nin` (each takes an array of scalars). Operators within one map are AND-combined, so `{"price":{"$gte":100,"$lte":500}}` expresses a closed range; `$in` and `$nin` may not be combined with other operators. Numbers and booleans are matched by type, so the field must have been ingested under a typed schema; dates may be sent as ISO 8601 strings or epoch milliseconds. Unknown operators, non-scalar operands, and malformed field names are rejected with a 400.

        text_mode : typing.Optional[SearchRequestTextMode]
            How query terms are matched by the keyword engine when the mode is TEXT or HYBRID. OR matches content containing any query term (broadest recall). AND requires every term to be present (higher precision). PHRASE requires the terms to appear as a contiguous sequence. COMPLEX enables the full query syntax, including boolean operators, field-scoped queries, and range filters. When omitted, defaults to PHRASE (with a slop of 3) in HYBRID mode and OR in TEXT mode.

        min_similarity : typing.Optional[float]
            The minimum semantic similarity score a result must have to be included, on a scale of 0.0 to 1.0. Results scoring below this threshold are dropped. Applies when the mode is SEMANTIC or HYBRID.

        min_text_relevance : typing.Optional[float]
            A relative relevance floor for the keyword leg, given as a fraction from 0 to 1 of the TOP result's score — results scoring below (top score × this value) are dropped. Keyword scores are unbounded and depend on the query, so this is a relative cutoff rather than an absolute score: for example, 0.5 keeps only results at least half as relevant as the best hit. Applies when the mode is TEXT or HYBRID. Omit it (or use a value of 0 or less) to keep all keyword matches.

        slop : typing.Optional[int]
            The phrase-match slop: the number of intervening positions allowed between query terms when `textMode` is PHRASE (0 means the terms must be exactly adjacent). Ignored for the other text modes.

        unique_documents : typing.Optional[bool]
            When true, returns at most one chunk per source item, so a single document or record cannot appear more than once in the results.

        content_types : typing.Optional[typing.Sequence[SearchRequestContentTypesItem]]
            Narrow results to specific content types. When omitted, empty, or set to both values, the search returns all content (documents and records) in a single unified result set, which is the default behavior. Each returned result carries a `sourceType` discriminator so you can tell documents and records apart. Pass `["documents"]` for documents only, or `["records"]` for records only.

        folder_id : typing.Optional[str]
            Restrict results to content (documents or records) in this EXACT folder. Folders hold a mix of documents and records. Provide the Vectros-assigned UUID of a folder; use `GET /v1/folders` to list your folders. To match a folder AND all of its descendants, use `rootFolderId` instead.

        root_folder_id : typing.Optional[str]
            Restrict results to content (documents or records) anywhere under this folder subtree — the folder itself and all of its descendants. Provide the Vectros-assigned UUID of a top-level (root) folder. Applies to documents and records alike. Use `folderId` instead to match a single exact folder.

        type_name : typing.Optional[str]
            Restrict results to records of a specific schema type (for example `patient` or `intake_form`). Has no effect on documents — it only narrows record results. Setting it implicitly limits the results to records, unless you also include documents via `contentTypes`.

        created_after : typing.Optional[str]
            Restrict results to content created at or after this ISO-8601 UTC timestamp. Useful for incremental queries (for example, finding anything ingested in the last hour), for isolating just-created content from older history, and for time-bounded analytics. Pair it with `createdBefore` to define a window.

        created_before : typing.Optional[str]
            Restrict results to content created at or before this ISO-8601 UTC timestamp. Pair it with `createdAfter` to define a window, or use it alone to find content older than a cutoff (for example, in archival or cleanup workflows).

        require_complete : typing.Optional[bool]
            A fail-closed override. When true, the request returns HTTP 503 instead of partial results if one of the search engines is unavailable. Defaults to false, in which case an outage degrades to the surviving engine and the response carries `degraded: true` along with the failed engines in `degradedLegs`. Set this to true only when complete results are required and a degraded answer is unacceptable.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchResponse]
            The matching results, ranked by relevance.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/search",
            method="POST",
            json={
                "query": query,
                "mode": mode,
                "limit": limit,
                "offset": offset,
                "userId": user_id,
                "orgId": org_id,
                "clientId": client_id,
                "filters": convert_and_respect_annotation_metadata(
                    object_=filters, annotation=typing.Dict[str, FilterValue], direction="write"
                ),
                "textMode": text_mode,
                "minSimilarity": min_similarity,
                "minTextRelevance": min_text_relevance,
                "slop": slop,
                "uniqueDocuments": unique_documents,
                "contentTypes": content_types,
                "folderId": folder_id,
                "rootFolderId": root_folder_id,
                "typeName": type_name,
                "createdAfter": created_after,
                "createdBefore": created_before,
                "requireComplete": require_complete,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchResponse,
                    parse_obj_as(
                        type_=SearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def content(
        self,
        *,
        query: str,
        mode: typing.Optional[SearchRequestMode] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        org_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, FilterValue]] = OMIT,
        text_mode: typing.Optional[SearchRequestTextMode] = OMIT,
        min_similarity: typing.Optional[float] = OMIT,
        min_text_relevance: typing.Optional[float] = OMIT,
        slop: typing.Optional[int] = OMIT,
        unique_documents: typing.Optional[bool] = OMIT,
        content_types: typing.Optional[typing.Sequence[SearchRequestContentTypesItem]] = OMIT,
        folder_id: typing.Optional[str] = OMIT,
        root_folder_id: typing.Optional[str] = OMIT,
        type_name: typing.Optional[str] = OMIT,
        created_after: typing.Optional[str] = OMIT,
        created_before: typing.Optional[str] = OMIT,
        require_complete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SearchResponse]:
        """
        Runs a hybrid, semantic, or text search across the content you have indexed. By default it returns both documents and records in a single unified result set; pass `contentTypes` to narrow the results (for example `["documents"]`). Each result carries a `sourceType` discriminator (`PartnerDocument` or `GenericRecord`) so you can branch on the type. Requires the `search:r` scope.

        Parameters
        ----------
        query : str
            The search query, expressed in natural language or as keywords. Required.

        mode : typing.Optional[SearchRequestMode]
            How results are ranked. HYBRID combines semantic and keyword ranking (recommended). SEMANTIC ranks by vector similarity only. TEXT ranks by keyword matching only. Defaults to HYBRID.

        limit : typing.Optional[int]
            The maximum number of results to return. Must be between 1 and 100. Defaults to 20.

        offset : typing.Optional[int]
            The number of results to skip, for pagination. Must be between 0 and 200. Defaults to 0.

        user_id : typing.Optional[str]
            Restrict results to content owned by this user — the Vectros-assigned UUID of a user in your account. Use `GET /v1/users?externalId=` to look up a user's ID from your own identifier.

        org_id : typing.Optional[str]
            Restrict results to content belonging to this organization — the Vectros-assigned UUID of an organization in your account. Use `GET /v1/orgs?externalId=` to look up an organization's ID from your own identifier.

        client_id : typing.Optional[str]
            Restrict results to content associated with this client — the Vectros-assigned UUID of a client in your account. Use `GET /v1/clients?externalId=` to look up a client's ID from your own identifier.

        filters : typing.Optional[typing.Dict[str, FilterValue]]
            Field-level filters applied to your document and record metadata. Each key is a field name, and top-level keys are AND-combined. Each value is one of: a scalar (string, number, or boolean) for an exact match; an array of scalars to match any one of them; or an operator map for ranges, negation, and membership. The supported operators are a closed set: `$eq`, `$ne`, `$gt`, `$gte`, `$lt`, `$lte` (each takes a scalar) and `$in`, `$nin` (each takes an array of scalars). Operators within one map are AND-combined, so `{"price":{"$gte":100,"$lte":500}}` expresses a closed range; `$in` and `$nin` may not be combined with other operators. Numbers and booleans are matched by type, so the field must have been ingested under a typed schema; dates may be sent as ISO 8601 strings or epoch milliseconds. Unknown operators, non-scalar operands, and malformed field names are rejected with a 400.

        text_mode : typing.Optional[SearchRequestTextMode]
            How query terms are matched by the keyword engine when the mode is TEXT or HYBRID. OR matches content containing any query term (broadest recall). AND requires every term to be present (higher precision). PHRASE requires the terms to appear as a contiguous sequence. COMPLEX enables the full query syntax, including boolean operators, field-scoped queries, and range filters. When omitted, defaults to PHRASE (with a slop of 3) in HYBRID mode and OR in TEXT mode.

        min_similarity : typing.Optional[float]
            The minimum semantic similarity score a result must have to be included, on a scale of 0.0 to 1.0. Results scoring below this threshold are dropped. Applies when the mode is SEMANTIC or HYBRID.

        min_text_relevance : typing.Optional[float]
            A relative relevance floor for the keyword leg, given as a fraction from 0 to 1 of the TOP result's score — results scoring below (top score × this value) are dropped. Keyword scores are unbounded and depend on the query, so this is a relative cutoff rather than an absolute score: for example, 0.5 keeps only results at least half as relevant as the best hit. Applies when the mode is TEXT or HYBRID. Omit it (or use a value of 0 or less) to keep all keyword matches.

        slop : typing.Optional[int]
            The phrase-match slop: the number of intervening positions allowed between query terms when `textMode` is PHRASE (0 means the terms must be exactly adjacent). Ignored for the other text modes.

        unique_documents : typing.Optional[bool]
            When true, returns at most one chunk per source item, so a single document or record cannot appear more than once in the results.

        content_types : typing.Optional[typing.Sequence[SearchRequestContentTypesItem]]
            Narrow results to specific content types. When omitted, empty, or set to both values, the search returns all content (documents and records) in a single unified result set, which is the default behavior. Each returned result carries a `sourceType` discriminator so you can tell documents and records apart. Pass `["documents"]` for documents only, or `["records"]` for records only.

        folder_id : typing.Optional[str]
            Restrict results to content (documents or records) in this EXACT folder. Folders hold a mix of documents and records. Provide the Vectros-assigned UUID of a folder; use `GET /v1/folders` to list your folders. To match a folder AND all of its descendants, use `rootFolderId` instead.

        root_folder_id : typing.Optional[str]
            Restrict results to content (documents or records) anywhere under this folder subtree — the folder itself and all of its descendants. Provide the Vectros-assigned UUID of a top-level (root) folder. Applies to documents and records alike. Use `folderId` instead to match a single exact folder.

        type_name : typing.Optional[str]
            Restrict results to records of a specific schema type (for example `patient` or `intake_form`). Has no effect on documents — it only narrows record results. Setting it implicitly limits the results to records, unless you also include documents via `contentTypes`.

        created_after : typing.Optional[str]
            Restrict results to content created at or after this ISO-8601 UTC timestamp. Useful for incremental queries (for example, finding anything ingested in the last hour), for isolating just-created content from older history, and for time-bounded analytics. Pair it with `createdBefore` to define a window.

        created_before : typing.Optional[str]
            Restrict results to content created at or before this ISO-8601 UTC timestamp. Pair it with `createdAfter` to define a window, or use it alone to find content older than a cutoff (for example, in archival or cleanup workflows).

        require_complete : typing.Optional[bool]
            A fail-closed override. When true, the request returns HTTP 503 instead of partial results if one of the search engines is unavailable. Defaults to false, in which case an outage degrades to the surviving engine and the response carries `degraded: true` along with the failed engines in `degradedLegs`. Set this to true only when complete results are required and a degraded answer is unacceptable.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchResponse]
            The matching results, ranked by relevance.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/search",
            method="POST",
            json={
                "query": query,
                "mode": mode,
                "limit": limit,
                "offset": offset,
                "userId": user_id,
                "orgId": org_id,
                "clientId": client_id,
                "filters": convert_and_respect_annotation_metadata(
                    object_=filters, annotation=typing.Dict[str, FilterValue], direction="write"
                ),
                "textMode": text_mode,
                "minSimilarity": min_similarity,
                "minTextRelevance": min_text_relevance,
                "slop": slop,
                "uniqueDocuments": unique_documents,
                "contentTypes": content_types,
                "folderId": folder_id,
                "rootFolderId": root_folder_id,
                "typeName": type_name,
                "createdAfter": created_after,
                "createdBefore": created_before,
                "requireComplete": require_complete,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchResponse,
                    parse_obj_as(
                        type_=SearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
