# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.firing_source_request import FiringSourceRequest
from ..types.scope_clause import ScopeClause
from ..types.script_ref_request import ScriptRefRequest
from ..types.trigger_failure_page import TriggerFailurePage
from ..types.trigger_rule_page import TriggerRulePage
from ..types.trigger_rule_response import TriggerRuleResponse
from .raw_client import AsyncRawTriggersClient, RawTriggersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TriggersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTriggersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTriggersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTriggersClient
        """
        return self._raw_client

    def list_trigger_failures(
        self,
        *,
        rule_id: typing.Optional[str] = None,
        category: typing.Optional[str] = None,
        retryable: typing.Optional[bool] = None,
        from_: typing.Optional[str] = None,
        to: typing.Optional[str] = None,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerFailurePage:
        """
        Returns a page of trigger executions that failed — what went wrong, whether the platform will retry it, and which of your records and rules were involved. Use this to find automation that has stopped running.

        A record appears once per FIRING, not once per attempt: if the platform retries a retryable failure, the same record's `attempts` count rises rather than a new record appearing. **If a retry later succeeds, the record is removed** — so this endpoint describes what is currently broken, not a permanent history. Records also expire 30 days after the firing first failed.

        `detail` is safe to surface to your own users: it carries only your own content (a script's own thrown message) or public API vocabulary, never platform internals. For `INTERNAL_ERROR` it is absent and a `correlationId` is returned instead — quote that to support.

        Scoped to your account and app context, derived from your token — never from input. Requires the `triggers:r` scope.

        Parameters
        ----------
        rule_id : typing.Optional[str]
            Return only failures of this trigger rule.

        category : typing.Optional[str]
            Return only failures in this category (e.g. `SCRIPT_ERROR`, `TIMEOUT`, `AUTHORIZATION_DENIED`). Case-insensitive.

        retryable : typing.Optional[bool]
            Return only failures the platform will retry (`true`) or will not (`false`).

        from_ : typing.Optional[str]
            Return only failures that first occurred at or after this ISO-8601 UTC timestamp.

        to : typing.Optional[str]
            Return only failures that first occurred before this ISO-8601 UTC timestamp.

        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` returned by the previous page to fetch the next page; omit it for the first page. The cursor is **opaque** — echo it back unchanged.

        limit : typing.Optional[int]
            Maximum number of failures to return per page. Must be between 1 and 100; defaults to 20.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerFailurePage
            A page of trigger execution failures, returned as a `{data, nextCursor}` envelope. `nextCursor` is null when there are no more pages.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.triggers.list_trigger_failures(
            rule_id="3b1c9f2e7a5d8410f6c2e9a1b7d4038f5e6a91c2d7f0b3a4586c9e2f1d0a7b3c",
            category="SCRIPT_ERROR",
            start_from="b3BhcXVlLWN1cnNvci1mcm9tLXRoZS1wcmV2aW91cy1wYWdl",
        )
        """
        _response = self._raw_client.list_trigger_failures(
            rule_id=rule_id,
            category=category,
            retryable=retryable,
            from_=from_,
            to=to,
            start_from=start_from,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def list_triggers(
        self,
        *,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerRulePage:
        """
        Returns a paginated list of your trigger rules, newest first. Results are returned as a `{data, nextCursor}` envelope — pass `nextCursor` as `startFrom` to fetch the next page. Requires the `triggers:r` scope.

        Parameters
        ----------
        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` returned by the previous page to fetch the next page; omit it for the first page. The cursor is **opaque** — echo it back unchanged.

        limit : typing.Optional[int]
            Maximum number of trigger rules to return per page. Must be between 1 and 100; defaults to 20.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRulePage
            A page of trigger rules, returned as a `{data, nextCursor}` envelope. `nextCursor` is null when there are no more pages.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.triggers.list_triggers(
            start_from="b3BhcXVlLWN1cnNvci1mcm9tLXRoZS1wcmV2aW91cy1wYWdl",
        )
        """
        _response = self._raw_client.list_triggers(start_from=start_from, limit=limit, request_options=request_options)
        return _response.data

    def create_trigger(
        self,
        *,
        name: str,
        firing_source: FiringSourceRequest,
        script_ref: ScriptRefRequest,
        upsert: typing.Optional[bool] = None,
        role_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        scopes: typing.Optional[typing.Sequence[ScopeClause]] = OMIT,
        manifest: typing.Optional[typing.Sequence[str]] = OMIT,
        fields: typing.Optional[typing.Sequence[str]] = OMIT,
        principal_id: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerRuleResponse:
        """
        Declares a new trigger rule, or (with `?upsert=true`) reconciles an existing one of the same name to the submitted shape. Once declared, the rule fires: a record write on the named schema dispatches the referenced script, which runs asynchronously under this rule's own grant. Because that grant is executed, a scoped credential may not declare a trigger whose grant exceeds its own — such a request is rejected with a `403`, and a `roleIds` entry that does not resolve in this context with a `400`. Requires the `triggers:c` scope (also `triggers:u` when `?upsert=true` matches an existing row).

        Parameters
        ----------
        name : str
            Your own identifier for the trigger rule, unique within your app context. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Immutable once created; ignored on update.

        firing_source : FiringSourceRequest

        script_ref : ScriptRefRequest

        upsert : typing.Optional[bool]
            When `true`, if a trigger rule with the same `name` already exists it is reconciled to the submitted shape instead of being returned unchanged. Defaults to `false`. Requires the `triggers:u` scope in addition to `triggers:c`.

        role_ids : typing.Optional[typing.Sequence[str]]
            Role composition — the trigger's principal is granted each named role's clauses, concatenated in the order listed. Mutually exclusive with 'scopes'; provide exactly one.

        scopes : typing.Optional[typing.Sequence[ScopeClause]]
            Inline scope clauses granted to this trigger's principal — the same shape a role's own clause list carries. Mutually exclusive with 'roleIds'; provide exactly one.

        manifest : typing.Optional[typing.Sequence[str]]
            Optional operation manifest: the host-object verbs this trigger's script may call (e.g. 'records.update'), narrowing its grant further for this usage only. ENFORCED at execution: a verb outside the manifest is refused even when the grant would allow it. An entry names one of the three host-object namespaces and one of its verbs — 'records.<verb>' and 'documents.<verb>' each offer create/get/update/delete/query/lookup, and 'folders.<verb>' offers create/get/update/delete/query (folders have no lookup). An unrecognized entry is rejected with a 400 listing the recognized set. On CREATE, omitting this field (or sending an empty list) means no manifest (the full grant applies). On UPDATE (PUT), omitting this field leaves the trigger's EXISTING manifest unchanged — it does NOT clear it; send an explicit empty list ([]) to remove a manifest restriction and return to the full grant.

        fields : typing.Optional[typing.Sequence[str]]
            REQUIRED on create: the record fields this rule projects into its script's `input.record` — and, on an UPDATE firing, `input.previous` (the same fields from the row before the write). On a DELETE firing `input.record` carries these fields from the deleted row, which is the only way a script can see anything of it. Send an empty list to project nothing beyond the record's identity (`input.recordId`). Every entry must name a field the schema keeps INLINE — declared `inline: true`, `filterable`, or as a lookup field — and not `sensitive`; anything else is rejected with a 400 listing the projectable fields, and a schema update that would un-inline a field a rule still projects is refused. A field the record does not carry is simply absent (`undefined`), never null. Together, `record` and `previous` are limited to 224 KB serialised; a firing whose projected input exceeds that is not run and is recorded as an `INPUT_TOO_LARGE` failure naming the size. A rule that declares fields must be able to READ every record it fires on: its grant must hold a records:r clause covering the schema's type (a grant with no read at all is rejected), and that clause may not carry a literal data_scope constraint (a `${{ input.userId }}` / `${{ input.scope.<namespace>}}` placeholder is fine — it is the firing record's own value), or the rule is rejected with a 400; and if at execution the rule's grant cannot read the firing record, `record` and `previous` are delivered as empty objects. On UPDATE (PUT), omitting this field leaves the trigger's existing declaration unchanged.

        principal_id : typing.Optional[str]
            The TYPE_SERVICE principal id minted for this trigger (set by the CLI loader at blueprint-apply time; not partner-authored directly in the normal flow, but accepted here so the loader can set it explicitly).

        provisioned_by : typing.Optional[str]
            The name of the blueprint that provisions this trigger. Set by `vectros bootstrap --blueprint` so that a later apply of the SAME blueprint can safely delete a trigger you have removed from it, and so that a trigger belonging to another blueprint — or hand-authored through this API — is never deleted by someone else's apply. Leave it unset for a trigger you manage yourself. Immutable once set: to move a trigger between blueprints, delete it and re-create it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRuleResponse
            An existing trigger rule of this name was returned (plain create) or reconciled (`?upsert=true`).

        Examples
        --------
        from vectros import FiringSourceRequest, ScriptRefRequest, VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.triggers.create_trigger(
            name="on-intake-create",
            firing_source=FiringSourceRequest(
                schema_id="sch_9f8e7d6c",
                event="CREATE",
            ),
            script_ref=ScriptRefRequest(
                name="notify-assignee",
                version="3",
            ),
        )
        """
        _response = self._raw_client.create_trigger(
            name=name,
            firing_source=firing_source,
            script_ref=script_ref,
            upsert=upsert,
            role_ids=role_ids,
            scopes=scopes,
            manifest=manifest,
            fields=fields,
            principal_id=principal_id,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    def get_trigger(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TriggerRuleResponse:
        """
        Retrieves a single trigger rule by its ID. Requires the `triggers:r` scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRuleResponse
            The trigger rule was found and returned.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.triggers.get_trigger(
            id="id",
        )
        """
        _response = self._raw_client.get_trigger(id, request_options=request_options)
        return _response.data

    def update_trigger(
        self,
        id: str,
        *,
        name: str,
        firing_source: FiringSourceRequest,
        script_ref: ScriptRefRequest,
        role_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        scopes: typing.Optional[typing.Sequence[ScopeClause]] = OMIT,
        manifest: typing.Optional[typing.Sequence[str]] = OMIT,
        fields: typing.Optional[typing.Sequence[str]] = OMIT,
        principal_id: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerRuleResponse:
        """
        Updates an existing trigger rule in place. The rule's resulting grant must be within your own granted scope — including a grant you did not change, because a trigger's other fields (its `scriptRef`, its `principalId`) determine what that grant executes. `name`, `principalId` and `provisionedBy` are immutable once set. Requires the `triggers:u` scope.

        Parameters
        ----------
        id : str

        name : str
            Your own identifier for the trigger rule, unique within your app context. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Immutable once created; ignored on update.

        firing_source : FiringSourceRequest

        script_ref : ScriptRefRequest

        role_ids : typing.Optional[typing.Sequence[str]]
            Role composition — the trigger's principal is granted each named role's clauses, concatenated in the order listed. Mutually exclusive with 'scopes'; provide exactly one.

        scopes : typing.Optional[typing.Sequence[ScopeClause]]
            Inline scope clauses granted to this trigger's principal — the same shape a role's own clause list carries. Mutually exclusive with 'roleIds'; provide exactly one.

        manifest : typing.Optional[typing.Sequence[str]]
            Optional operation manifest: the host-object verbs this trigger's script may call (e.g. 'records.update'), narrowing its grant further for this usage only. ENFORCED at execution: a verb outside the manifest is refused even when the grant would allow it. An entry names one of the three host-object namespaces and one of its verbs — 'records.<verb>' and 'documents.<verb>' each offer create/get/update/delete/query/lookup, and 'folders.<verb>' offers create/get/update/delete/query (folders have no lookup). An unrecognized entry is rejected with a 400 listing the recognized set. On CREATE, omitting this field (or sending an empty list) means no manifest (the full grant applies). On UPDATE (PUT), omitting this field leaves the trigger's EXISTING manifest unchanged — it does NOT clear it; send an explicit empty list ([]) to remove a manifest restriction and return to the full grant.

        fields : typing.Optional[typing.Sequence[str]]
            REQUIRED on create: the record fields this rule projects into its script's `input.record` — and, on an UPDATE firing, `input.previous` (the same fields from the row before the write). On a DELETE firing `input.record` carries these fields from the deleted row, which is the only way a script can see anything of it. Send an empty list to project nothing beyond the record's identity (`input.recordId`). Every entry must name a field the schema keeps INLINE — declared `inline: true`, `filterable`, or as a lookup field — and not `sensitive`; anything else is rejected with a 400 listing the projectable fields, and a schema update that would un-inline a field a rule still projects is refused. A field the record does not carry is simply absent (`undefined`), never null. Together, `record` and `previous` are limited to 224 KB serialised; a firing whose projected input exceeds that is not run and is recorded as an `INPUT_TOO_LARGE` failure naming the size. A rule that declares fields must be able to READ every record it fires on: its grant must hold a records:r clause covering the schema's type (a grant with no read at all is rejected), and that clause may not carry a literal data_scope constraint (a `${{ input.userId }}` / `${{ input.scope.<namespace>}}` placeholder is fine — it is the firing record's own value), or the rule is rejected with a 400; and if at execution the rule's grant cannot read the firing record, `record` and `previous` are delivered as empty objects. On UPDATE (PUT), omitting this field leaves the trigger's existing declaration unchanged.

        principal_id : typing.Optional[str]
            The TYPE_SERVICE principal id minted for this trigger (set by the CLI loader at blueprint-apply time; not partner-authored directly in the normal flow, but accepted here so the loader can set it explicitly).

        provisioned_by : typing.Optional[str]
            The name of the blueprint that provisions this trigger. Set by `vectros bootstrap --blueprint` so that a later apply of the SAME blueprint can safely delete a trigger you have removed from it, and so that a trigger belonging to another blueprint — or hand-authored through this API — is never deleted by someone else's apply. Leave it unset for a trigger you manage yourself. Immutable once set: to move a trigger between blueprints, delete it and re-create it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRuleResponse
            The trigger rule was updated.

        Examples
        --------
        from vectros import FiringSourceRequest, ScriptRefRequest, VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.triggers.update_trigger(
            id="id",
            name="on-intake-create",
            firing_source=FiringSourceRequest(
                schema_id="sch_9f8e7d6c",
                event="CREATE",
            ),
            script_ref=ScriptRefRequest(
                name="notify-assignee",
                version="3",
            ),
        )
        """
        _response = self._raw_client.update_trigger(
            id,
            name=name,
            firing_source=firing_source,
            script_ref=script_ref,
            role_ids=role_ids,
            scopes=scopes,
            manifest=manifest,
            fields=fields,
            principal_id=principal_id,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    def delete_trigger(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes one trigger rule by ID. Requires the `triggers:d` scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.triggers.delete_trigger(
            id="id",
        )
        """
        _response = self._raw_client.delete_trigger(id, request_options=request_options)
        return _response.data


class AsyncTriggersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTriggersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTriggersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTriggersClient
        """
        return self._raw_client

    async def list_trigger_failures(
        self,
        *,
        rule_id: typing.Optional[str] = None,
        category: typing.Optional[str] = None,
        retryable: typing.Optional[bool] = None,
        from_: typing.Optional[str] = None,
        to: typing.Optional[str] = None,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerFailurePage:
        """
        Returns a page of trigger executions that failed — what went wrong, whether the platform will retry it, and which of your records and rules were involved. Use this to find automation that has stopped running.

        A record appears once per FIRING, not once per attempt: if the platform retries a retryable failure, the same record's `attempts` count rises rather than a new record appearing. **If a retry later succeeds, the record is removed** — so this endpoint describes what is currently broken, not a permanent history. Records also expire 30 days after the firing first failed.

        `detail` is safe to surface to your own users: it carries only your own content (a script's own thrown message) or public API vocabulary, never platform internals. For `INTERNAL_ERROR` it is absent and a `correlationId` is returned instead — quote that to support.

        Scoped to your account and app context, derived from your token — never from input. Requires the `triggers:r` scope.

        Parameters
        ----------
        rule_id : typing.Optional[str]
            Return only failures of this trigger rule.

        category : typing.Optional[str]
            Return only failures in this category (e.g. `SCRIPT_ERROR`, `TIMEOUT`, `AUTHORIZATION_DENIED`). Case-insensitive.

        retryable : typing.Optional[bool]
            Return only failures the platform will retry (`true`) or will not (`false`).

        from_ : typing.Optional[str]
            Return only failures that first occurred at or after this ISO-8601 UTC timestamp.

        to : typing.Optional[str]
            Return only failures that first occurred before this ISO-8601 UTC timestamp.

        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` returned by the previous page to fetch the next page; omit it for the first page. The cursor is **opaque** — echo it back unchanged.

        limit : typing.Optional[int]
            Maximum number of failures to return per page. Must be between 1 and 100; defaults to 20.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerFailurePage
            A page of trigger execution failures, returned as a `{data, nextCursor}` envelope. `nextCursor` is null when there are no more pages.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.triggers.list_trigger_failures(
                rule_id="3b1c9f2e7a5d8410f6c2e9a1b7d4038f5e6a91c2d7f0b3a4586c9e2f1d0a7b3c",
                category="SCRIPT_ERROR",
                start_from="b3BhcXVlLWN1cnNvci1mcm9tLXRoZS1wcmV2aW91cy1wYWdl",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_trigger_failures(
            rule_id=rule_id,
            category=category,
            retryable=retryable,
            from_=from_,
            to=to,
            start_from=start_from,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def list_triggers(
        self,
        *,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerRulePage:
        """
        Returns a paginated list of your trigger rules, newest first. Results are returned as a `{data, nextCursor}` envelope — pass `nextCursor` as `startFrom` to fetch the next page. Requires the `triggers:r` scope.

        Parameters
        ----------
        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` returned by the previous page to fetch the next page; omit it for the first page. The cursor is **opaque** — echo it back unchanged.

        limit : typing.Optional[int]
            Maximum number of trigger rules to return per page. Must be between 1 and 100; defaults to 20.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRulePage
            A page of trigger rules, returned as a `{data, nextCursor}` envelope. `nextCursor` is null when there are no more pages.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.triggers.list_triggers(
                start_from="b3BhcXVlLWN1cnNvci1mcm9tLXRoZS1wcmV2aW91cy1wYWdl",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_triggers(
            start_from=start_from, limit=limit, request_options=request_options
        )
        return _response.data

    async def create_trigger(
        self,
        *,
        name: str,
        firing_source: FiringSourceRequest,
        script_ref: ScriptRefRequest,
        upsert: typing.Optional[bool] = None,
        role_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        scopes: typing.Optional[typing.Sequence[ScopeClause]] = OMIT,
        manifest: typing.Optional[typing.Sequence[str]] = OMIT,
        fields: typing.Optional[typing.Sequence[str]] = OMIT,
        principal_id: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerRuleResponse:
        """
        Declares a new trigger rule, or (with `?upsert=true`) reconciles an existing one of the same name to the submitted shape. Once declared, the rule fires: a record write on the named schema dispatches the referenced script, which runs asynchronously under this rule's own grant. Because that grant is executed, a scoped credential may not declare a trigger whose grant exceeds its own — such a request is rejected with a `403`, and a `roleIds` entry that does not resolve in this context with a `400`. Requires the `triggers:c` scope (also `triggers:u` when `?upsert=true` matches an existing row).

        Parameters
        ----------
        name : str
            Your own identifier for the trigger rule, unique within your app context. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Immutable once created; ignored on update.

        firing_source : FiringSourceRequest

        script_ref : ScriptRefRequest

        upsert : typing.Optional[bool]
            When `true`, if a trigger rule with the same `name` already exists it is reconciled to the submitted shape instead of being returned unchanged. Defaults to `false`. Requires the `triggers:u` scope in addition to `triggers:c`.

        role_ids : typing.Optional[typing.Sequence[str]]
            Role composition — the trigger's principal is granted each named role's clauses, concatenated in the order listed. Mutually exclusive with 'scopes'; provide exactly one.

        scopes : typing.Optional[typing.Sequence[ScopeClause]]
            Inline scope clauses granted to this trigger's principal — the same shape a role's own clause list carries. Mutually exclusive with 'roleIds'; provide exactly one.

        manifest : typing.Optional[typing.Sequence[str]]
            Optional operation manifest: the host-object verbs this trigger's script may call (e.g. 'records.update'), narrowing its grant further for this usage only. ENFORCED at execution: a verb outside the manifest is refused even when the grant would allow it. An entry names one of the three host-object namespaces and one of its verbs — 'records.<verb>' and 'documents.<verb>' each offer create/get/update/delete/query/lookup, and 'folders.<verb>' offers create/get/update/delete/query (folders have no lookup). An unrecognized entry is rejected with a 400 listing the recognized set. On CREATE, omitting this field (or sending an empty list) means no manifest (the full grant applies). On UPDATE (PUT), omitting this field leaves the trigger's EXISTING manifest unchanged — it does NOT clear it; send an explicit empty list ([]) to remove a manifest restriction and return to the full grant.

        fields : typing.Optional[typing.Sequence[str]]
            REQUIRED on create: the record fields this rule projects into its script's `input.record` — and, on an UPDATE firing, `input.previous` (the same fields from the row before the write). On a DELETE firing `input.record` carries these fields from the deleted row, which is the only way a script can see anything of it. Send an empty list to project nothing beyond the record's identity (`input.recordId`). Every entry must name a field the schema keeps INLINE — declared `inline: true`, `filterable`, or as a lookup field — and not `sensitive`; anything else is rejected with a 400 listing the projectable fields, and a schema update that would un-inline a field a rule still projects is refused. A field the record does not carry is simply absent (`undefined`), never null. Together, `record` and `previous` are limited to 224 KB serialised; a firing whose projected input exceeds that is not run and is recorded as an `INPUT_TOO_LARGE` failure naming the size. A rule that declares fields must be able to READ every record it fires on: its grant must hold a records:r clause covering the schema's type (a grant with no read at all is rejected), and that clause may not carry a literal data_scope constraint (a `${{ input.userId }}` / `${{ input.scope.<namespace>}}` placeholder is fine — it is the firing record's own value), or the rule is rejected with a 400; and if at execution the rule's grant cannot read the firing record, `record` and `previous` are delivered as empty objects. On UPDATE (PUT), omitting this field leaves the trigger's existing declaration unchanged.

        principal_id : typing.Optional[str]
            The TYPE_SERVICE principal id minted for this trigger (set by the CLI loader at blueprint-apply time; not partner-authored directly in the normal flow, but accepted here so the loader can set it explicitly).

        provisioned_by : typing.Optional[str]
            The name of the blueprint that provisions this trigger. Set by `vectros bootstrap --blueprint` so that a later apply of the SAME blueprint can safely delete a trigger you have removed from it, and so that a trigger belonging to another blueprint — or hand-authored through this API — is never deleted by someone else's apply. Leave it unset for a trigger you manage yourself. Immutable once set: to move a trigger between blueprints, delete it and re-create it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRuleResponse
            An existing trigger rule of this name was returned (plain create) or reconciled (`?upsert=true`).

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi, FiringSourceRequest, ScriptRefRequest

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.triggers.create_trigger(
                name="on-intake-create",
                firing_source=FiringSourceRequest(
                    schema_id="sch_9f8e7d6c",
                    event="CREATE",
                ),
                script_ref=ScriptRefRequest(
                    name="notify-assignee",
                    version="3",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_trigger(
            name=name,
            firing_source=firing_source,
            script_ref=script_ref,
            upsert=upsert,
            role_ids=role_ids,
            scopes=scopes,
            manifest=manifest,
            fields=fields,
            principal_id=principal_id,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    async def get_trigger(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TriggerRuleResponse:
        """
        Retrieves a single trigger rule by its ID. Requires the `triggers:r` scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRuleResponse
            The trigger rule was found and returned.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.triggers.get_trigger(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_trigger(id, request_options=request_options)
        return _response.data

    async def update_trigger(
        self,
        id: str,
        *,
        name: str,
        firing_source: FiringSourceRequest,
        script_ref: ScriptRefRequest,
        role_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        scopes: typing.Optional[typing.Sequence[ScopeClause]] = OMIT,
        manifest: typing.Optional[typing.Sequence[str]] = OMIT,
        fields: typing.Optional[typing.Sequence[str]] = OMIT,
        principal_id: typing.Optional[str] = OMIT,
        provisioned_by: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TriggerRuleResponse:
        """
        Updates an existing trigger rule in place. The rule's resulting grant must be within your own granted scope — including a grant you did not change, because a trigger's other fields (its `scriptRef`, its `principalId`) determine what that grant executes. `name`, `principalId` and `provisionedBy` are immutable once set. Requires the `triggers:u` scope.

        Parameters
        ----------
        id : str

        name : str
            Your own identifier for the trigger rule, unique within your app context. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Immutable once created; ignored on update.

        firing_source : FiringSourceRequest

        script_ref : ScriptRefRequest

        role_ids : typing.Optional[typing.Sequence[str]]
            Role composition — the trigger's principal is granted each named role's clauses, concatenated in the order listed. Mutually exclusive with 'scopes'; provide exactly one.

        scopes : typing.Optional[typing.Sequence[ScopeClause]]
            Inline scope clauses granted to this trigger's principal — the same shape a role's own clause list carries. Mutually exclusive with 'roleIds'; provide exactly one.

        manifest : typing.Optional[typing.Sequence[str]]
            Optional operation manifest: the host-object verbs this trigger's script may call (e.g. 'records.update'), narrowing its grant further for this usage only. ENFORCED at execution: a verb outside the manifest is refused even when the grant would allow it. An entry names one of the three host-object namespaces and one of its verbs — 'records.<verb>' and 'documents.<verb>' each offer create/get/update/delete/query/lookup, and 'folders.<verb>' offers create/get/update/delete/query (folders have no lookup). An unrecognized entry is rejected with a 400 listing the recognized set. On CREATE, omitting this field (or sending an empty list) means no manifest (the full grant applies). On UPDATE (PUT), omitting this field leaves the trigger's EXISTING manifest unchanged — it does NOT clear it; send an explicit empty list ([]) to remove a manifest restriction and return to the full grant.

        fields : typing.Optional[typing.Sequence[str]]
            REQUIRED on create: the record fields this rule projects into its script's `input.record` — and, on an UPDATE firing, `input.previous` (the same fields from the row before the write). On a DELETE firing `input.record` carries these fields from the deleted row, which is the only way a script can see anything of it. Send an empty list to project nothing beyond the record's identity (`input.recordId`). Every entry must name a field the schema keeps INLINE — declared `inline: true`, `filterable`, or as a lookup field — and not `sensitive`; anything else is rejected with a 400 listing the projectable fields, and a schema update that would un-inline a field a rule still projects is refused. A field the record does not carry is simply absent (`undefined`), never null. Together, `record` and `previous` are limited to 224 KB serialised; a firing whose projected input exceeds that is not run and is recorded as an `INPUT_TOO_LARGE` failure naming the size. A rule that declares fields must be able to READ every record it fires on: its grant must hold a records:r clause covering the schema's type (a grant with no read at all is rejected), and that clause may not carry a literal data_scope constraint (a `${{ input.userId }}` / `${{ input.scope.<namespace>}}` placeholder is fine — it is the firing record's own value), or the rule is rejected with a 400; and if at execution the rule's grant cannot read the firing record, `record` and `previous` are delivered as empty objects. On UPDATE (PUT), omitting this field leaves the trigger's existing declaration unchanged.

        principal_id : typing.Optional[str]
            The TYPE_SERVICE principal id minted for this trigger (set by the CLI loader at blueprint-apply time; not partner-authored directly in the normal flow, but accepted here so the loader can set it explicitly).

        provisioned_by : typing.Optional[str]
            The name of the blueprint that provisions this trigger. Set by `vectros bootstrap --blueprint` so that a later apply of the SAME blueprint can safely delete a trigger you have removed from it, and so that a trigger belonging to another blueprint — or hand-authored through this API — is never deleted by someone else's apply. Leave it unset for a trigger you manage yourself. Immutable once set: to move a trigger between blueprints, delete it and re-create it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TriggerRuleResponse
            The trigger rule was updated.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi, FiringSourceRequest, ScriptRefRequest

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.triggers.update_trigger(
                id="id",
                name="on-intake-create",
                firing_source=FiringSourceRequest(
                    schema_id="sch_9f8e7d6c",
                    event="CREATE",
                ),
                script_ref=ScriptRefRequest(
                    name="notify-assignee",
                    version="3",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_trigger(
            id,
            name=name,
            firing_source=firing_source,
            script_ref=script_ref,
            role_ids=role_ids,
            scopes=scopes,
            manifest=manifest,
            fields=fields,
            principal_id=principal_id,
            provisioned_by=provisioned_by,
            request_options=request_options,
        )
        return _response.data

    async def delete_trigger(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes one trigger rule by ID. Requires the `triggers:d` scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.triggers.delete_trigger(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_trigger(id, request_options=request_options)
        return _response.data
