# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..types.field_def import FieldDef
from ..types.lookup_def import LookupDef
from ..types.model_data_version_page import ModelDataVersionPage
from ..types.render_hint_def import RenderHintDef
from ..types.schema_page import SchemaPage
from ..types.schema_request_allowed_surfaces_item import SchemaRequestAllowedSurfacesItem
from ..types.schema_request_index_mode import SchemaRequestIndexMode
from ..types.schema_request_storage_profile import SchemaRequestStorageProfile
from ..types.schema_response import SchemaResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSchemasClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_schemas(
        self,
        *,
        user_id: typing.Optional[str] = None,
        org_id: typing.Optional[str] = None,
        surface: typing.Optional[str] = None,
        record_type: typing.Optional[str] = None,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SchemaPage]:
        """
        Returns a paginated list of the record schemas defined in your account. Filter by `userId` or `orgId` to scope to an owner, by `surface` to list the types bindable to one surface, or by `recordType` to resolve the single schema for a type directly. Filtering by an identity surface (user, org, or client) lists your account-wide identity schemas regardless of the calling context; filtering by record or document lists within the calling context. Requires the `schemas:r` scope.

        Parameters
        ----------
        user_id : typing.Optional[str]
            Filter to schemas owned by this user — the Vectros-assigned UUID of a user in your account. Use `GET /v1/users?externalId=` to resolve a UUID from your own external id.

        org_id : typing.Optional[str]
            Filter to schemas owned by this organization — the Vectros-assigned UUID of an organization in your account. Use `GET /v1/orgs?externalId=` to resolve a UUID from your own external id.

        surface : typing.Optional[str]
            Filter to schemas bindable to this surface: record, document, user, org, or client. Returns only schemas whose allowed surfaces include the given one — useful for listing, say, document types separately from record types. The identity surfaces (user, org, client) are account-wide: filtering by one lists your account's identity schemas regardless of the calling context, whereas record and document list within the calling context.

        record_type : typing.Optional[str]
            Resolve the single schema for this record type — the natural handle for a schema, and the direct alternative to remembering its opaque id. Returns a one-element page, or an empty page if no such schema exists. Resolved in the calling context for record and document types; combine with `surface=user`, `org`, or `client` to resolve an account-wide identity schema. Mutually exclusive with `userId`/`orgId` — when supplied, `recordType` takes precedence.

        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` from the previous page to fetch the next page; omit it for the first page.

        limit : typing.Optional[int]
            Maximum number of schemas to return per page (1–100; defaults to 20).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchemaPage]
            A paginated list of schemas, as a `{data, nextCursor}` envelope.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/schemas",
            method="GET",
            params={
                "userId": user_id,
                "orgId": org_id,
                "surface": surface,
                "recordType": record_type,
                "startFrom": start_from,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaPage,
                    parse_obj_as(
                        type_=SchemaPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_schema(
        self,
        *,
        type_name: str,
        display_name: str,
        allowed_surfaces: typing.Sequence[SchemaRequestAllowedSurfacesItem],
        upsert: typing.Optional[bool] = None,
        description: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[FieldDef]] = OMIT,
        lookup_fields: typing.Optional[typing.Sequence[LookupDef]] = OMIT,
        render_hints: typing.Optional[typing.Dict[str, RenderHintDef]] = OMIT,
        capabilities: typing.Optional[typing.Dict[str, bool]] = OMIT,
        index_mode: typing.Optional[SchemaRequestIndexMode] = OMIT,
        storage_profile: typing.Optional[SchemaRequestStorageProfile] = OMIT,
        active: typing.Optional[bool] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        org_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SchemaResponse]:
        """
        Defines a new record type with optional field definitions, validation rules, and lookup indexes. Idempotent by `typeName` within the same ownership scope: re-creating an existing `typeName` returns the existing schema rather than failing. The response's `created` field (and the HTTP status — 201 when created, 200 when an existing schema was returned) tells the two apart. To reconcile an existing schema to the submitted shape instead of returning it unchanged, set `?upsert=true` (this also requires the `schemas:w` scope; only legal schema changes are applied — migration-locked changes are rejected). Requires the `schemas:w` scope.

        Parameters
        ----------
        type_name : str
            Unique type identifier for this schema. Immutable after creation.

        display_name : str
            Human-readable display name for this type, shown in UIs.

        allowed_surfaces : typing.Sequence[SchemaRequestAllowedSurfacesItem]
            Which typed surfaces may bind this schema by its id: record, document, user, org, or client. Required and must be non-empty. A schema may list several surfaces (for a shared type usable on both records and documents). This drives surface-scoped schema listing (`GET /v1/schemas?surface=`) and is enforced at bind time — for example, a document cannot bind a record-only schema.

        upsert : typing.Optional[bool]
            When `true`, if a schema with the same `typeName` already exists it is reconciled to the submitted shape (additive fields, lookups, renderHints, and `active` are applied) instead of being returned unchanged; `typeName` and migration-locked lookup attributes (`rangeEnabled`/`sortBy`/`sensitive`) cannot be changed and a request to do so is rejected. A re-applied upsert whose declared shape is unchanged is a no-op (no schema-version bump). Defaults to `false`. Requires the `schemas:w` scope.

        description : typing.Optional[str]
            Optional description of what this schema is for.

        fields : typing.Optional[typing.Sequence[FieldDef]]
            Field definitions used to validate record payloads. Omit for a bare schema that performs no payload validation.

        lookup_fields : typing.Optional[typing.Sequence[LookupDef]]
            Payload fields to index for direct lookup queries. Maximum 10 lookup fields.

        render_hints : typing.Optional[typing.Dict[str, RenderHintDef]]
            UI rendering hints keyed by field id.

        capabilities : typing.Optional[typing.Dict[str, bool]]
            Feature flags for this schema. `auditHistory` (default true) controls whether a change-history (version) trail is kept for this type's data; setting it false stops recording the trail but never affects your record or document data itself. `readAccessLog` (default false; opt-in) controls accounting-of-disclosures logging: when true, each governed read of this schema's records writes a retained, subject-enumerable access record. The effective value resolves in order: this schema flag, then your context's default, then the platform default (false).

        index_mode : typing.Optional[SchemaRequestIndexMode]
            Default search-index mode for instances of this type — applies to records of this type and to documents bound to this schema, unless the individual record or document sets its own indexMode. HYBRID, SEMANTIC, and TEXT make content searchable; NONE is store-only (the data is persisted, retrievable, and usable for lookups, but not searchable). Omit for no default: a record with no indexMode of its own then defaults to NONE, and a document with no indexMode is rejected.

        storage_profile : typing.Optional[SchemaRequestStorageProfile]
            Where this type's payload is stored. STANDARD (default): payloads of 4 KB or larger are externalized to S3, smaller ones are stored inline. LOW_LATENCY: always store inline for the lowest read latency. LARGE_PAYLOAD: always externalize to S3, which lifts the 400 KB item-size ceiling. For externalized types, list and lookup responses return only the indexed projection unless you pass `includePayload=true`.

        active : typing.Optional[bool]
            Whether this schema is active. An inactive schema rejects creation of new records of its type.

        user_id : typing.Optional[str]
            Owning user — the Vectros-assigned UUID of a user in your account. Optional; omit to create an account-wide shared schema. With an API key, this sets the schema's owner explicitly. With a scoped token, the user must match the token's identity claim (if set) or fall within the token's data scope.

        org_id : typing.Optional[str]
            Owning organization — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, this sets the schema's owning organization explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        client_id : typing.Optional[str]
            Associated client — the Vectros-assigned UUID of a client in your account. Optional. With an API key, this sets the schema's client explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchemaResponse]
            A schema with the same `typeName` already existed and was returned (`created: false`) — unchanged for an idempotent create, or reconciled when `?upsert=true`.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/schemas",
            method="POST",
            params={
                "upsert": upsert,
            },
            json={
                "typeName": type_name,
                "displayName": display_name,
                "description": description,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Sequence[FieldDef], direction="write"
                ),
                "lookupFields": convert_and_respect_annotation_metadata(
                    object_=lookup_fields, annotation=typing.Sequence[LookupDef], direction="write"
                ),
                "renderHints": convert_and_respect_annotation_metadata(
                    object_=render_hints, annotation=typing.Dict[str, RenderHintDef], direction="write"
                ),
                "capabilities": capabilities,
                "indexMode": index_mode,
                "storageProfile": storage_profile,
                "allowedSurfaces": allowed_surfaces,
                "active": active,
                "userId": user_id,
                "orgId": org_id,
                "clientId": client_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaResponse,
                    parse_obj_as(
                        type_=SchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_schema(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SchemaResponse]:
        """
        Retrieves a single record schema by its id. Requires the `schemas:r` scope.

        Parameters
        ----------
        id : str
            The id of the schema to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchemaResponse]
            The requested schema.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaResponse,
                    parse_obj_as(
                        type_=SchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_schema(
        self,
        id: str,
        *,
        type_name: str,
        display_name: str,
        allowed_surfaces: typing.Sequence[SchemaRequestAllowedSurfacesItem],
        description: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[FieldDef]] = OMIT,
        lookup_fields: typing.Optional[typing.Sequence[LookupDef]] = OMIT,
        render_hints: typing.Optional[typing.Dict[str, RenderHintDef]] = OMIT,
        capabilities: typing.Optional[typing.Dict[str, bool]] = OMIT,
        index_mode: typing.Optional[SchemaRequestIndexMode] = OMIT,
        storage_profile: typing.Optional[SchemaRequestStorageProfile] = OMIT,
        active: typing.Optional[bool] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        org_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SchemaResponse]:
        """
        Updates a record schema. Fields you omit are preserved; `typeName` is immutable and cannot be changed. Collection fields (`fields`, `lookupFields`, `renderHints`, `capabilities`) are replaced in full when supplied. Requires the `schemas:w` scope.

        Parameters
        ----------
        id : str
            The id of the schema to update.

        type_name : str
            Unique type identifier for this schema. Immutable after creation.

        display_name : str
            Human-readable display name for this type, shown in UIs.

        allowed_surfaces : typing.Sequence[SchemaRequestAllowedSurfacesItem]
            Which typed surfaces may bind this schema by its id: record, document, user, org, or client. Required and must be non-empty. A schema may list several surfaces (for a shared type usable on both records and documents). This drives surface-scoped schema listing (`GET /v1/schemas?surface=`) and is enforced at bind time — for example, a document cannot bind a record-only schema.

        description : typing.Optional[str]
            Optional description of what this schema is for.

        fields : typing.Optional[typing.Sequence[FieldDef]]
            Field definitions used to validate record payloads. Omit for a bare schema that performs no payload validation.

        lookup_fields : typing.Optional[typing.Sequence[LookupDef]]
            Payload fields to index for direct lookup queries. Maximum 10 lookup fields.

        render_hints : typing.Optional[typing.Dict[str, RenderHintDef]]
            UI rendering hints keyed by field id.

        capabilities : typing.Optional[typing.Dict[str, bool]]
            Feature flags for this schema. `auditHistory` (default true) controls whether a change-history (version) trail is kept for this type's data; setting it false stops recording the trail but never affects your record or document data itself. `readAccessLog` (default false; opt-in) controls accounting-of-disclosures logging: when true, each governed read of this schema's records writes a retained, subject-enumerable access record. The effective value resolves in order: this schema flag, then your context's default, then the platform default (false).

        index_mode : typing.Optional[SchemaRequestIndexMode]
            Default search-index mode for instances of this type — applies to records of this type and to documents bound to this schema, unless the individual record or document sets its own indexMode. HYBRID, SEMANTIC, and TEXT make content searchable; NONE is store-only (the data is persisted, retrievable, and usable for lookups, but not searchable). Omit for no default: a record with no indexMode of its own then defaults to NONE, and a document with no indexMode is rejected.

        storage_profile : typing.Optional[SchemaRequestStorageProfile]
            Where this type's payload is stored. STANDARD (default): payloads of 4 KB or larger are externalized to S3, smaller ones are stored inline. LOW_LATENCY: always store inline for the lowest read latency. LARGE_PAYLOAD: always externalize to S3, which lifts the 400 KB item-size ceiling. For externalized types, list and lookup responses return only the indexed projection unless you pass `includePayload=true`.

        active : typing.Optional[bool]
            Whether this schema is active. An inactive schema rejects creation of new records of its type.

        user_id : typing.Optional[str]
            Owning user — the Vectros-assigned UUID of a user in your account. Optional; omit to create an account-wide shared schema. With an API key, this sets the schema's owner explicitly. With a scoped token, the user must match the token's identity claim (if set) or fall within the token's data scope.

        org_id : typing.Optional[str]
            Owning organization — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, this sets the schema's owning organization explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        client_id : typing.Optional[str]
            Associated client — the Vectros-assigned UUID of a client in your account. Optional. With an API key, this sets the schema's client explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchemaResponse]
            The updated schema.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}",
            method="PUT",
            json={
                "typeName": type_name,
                "displayName": display_name,
                "description": description,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Sequence[FieldDef], direction="write"
                ),
                "lookupFields": convert_and_respect_annotation_metadata(
                    object_=lookup_fields, annotation=typing.Sequence[LookupDef], direction="write"
                ),
                "renderHints": convert_and_respect_annotation_metadata(
                    object_=render_hints, annotation=typing.Dict[str, RenderHintDef], direction="write"
                ),
                "capabilities": capabilities,
                "indexMode": index_mode,
                "storageProfile": storage_profile,
                "allowedSurfaces": allowed_surfaces,
                "active": active,
                "userId": user_id,
                "orgId": org_id,
                "clientId": client_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaResponse,
                    parse_obj_as(
                        type_=SchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_schema(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[None]:
        """
        Permanently deletes a record schema. The request is refused with 409 if records of this type still exist — delete those records first, since every record must reference a live schema. Requires the `schemas:w` scope.

        Parameters
        ----------
        id : str
            The id of the schema to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_schema_versions(
        self,
        id: str,
        *,
        start_from: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDataVersionPage]:
        """
        Returns the audit trail of changes to a record schema, newest first (create, update, and delete). Schema version history is always recorded — there is no per-schema toggle to disable it. Requires the `schemas:r` scope.

        Parameters
        ----------
        id : str
            The id of the schema whose version history you want.

        start_from : typing.Optional[str]
            Pagination cursor — pass the `nextCursor` value from the previous page to fetch the next one.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDataVersionPage]
            A paginated version history, as a `{data, nextCursor}` envelope.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}/versions",
            method="GET",
            params={
                "startFrom": start_from,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDataVersionPage,
                    parse_obj_as(
                        type_=ModelDataVersionPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSchemasClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_schemas(
        self,
        *,
        user_id: typing.Optional[str] = None,
        org_id: typing.Optional[str] = None,
        surface: typing.Optional[str] = None,
        record_type: typing.Optional[str] = None,
        start_from: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SchemaPage]:
        """
        Returns a paginated list of the record schemas defined in your account. Filter by `userId` or `orgId` to scope to an owner, by `surface` to list the types bindable to one surface, or by `recordType` to resolve the single schema for a type directly. Filtering by an identity surface (user, org, or client) lists your account-wide identity schemas regardless of the calling context; filtering by record or document lists within the calling context. Requires the `schemas:r` scope.

        Parameters
        ----------
        user_id : typing.Optional[str]
            Filter to schemas owned by this user — the Vectros-assigned UUID of a user in your account. Use `GET /v1/users?externalId=` to resolve a UUID from your own external id.

        org_id : typing.Optional[str]
            Filter to schemas owned by this organization — the Vectros-assigned UUID of an organization in your account. Use `GET /v1/orgs?externalId=` to resolve a UUID from your own external id.

        surface : typing.Optional[str]
            Filter to schemas bindable to this surface: record, document, user, org, or client. Returns only schemas whose allowed surfaces include the given one — useful for listing, say, document types separately from record types. The identity surfaces (user, org, client) are account-wide: filtering by one lists your account's identity schemas regardless of the calling context, whereas record and document list within the calling context.

        record_type : typing.Optional[str]
            Resolve the single schema for this record type — the natural handle for a schema, and the direct alternative to remembering its opaque id. Returns a one-element page, or an empty page if no such schema exists. Resolved in the calling context for record and document types; combine with `surface=user`, `org`, or `client` to resolve an account-wide identity schema. Mutually exclusive with `userId`/`orgId` — when supplied, `recordType` takes precedence.

        start_from : typing.Optional[str]
            Pagination cursor. Pass the `nextCursor` from the previous page to fetch the next page; omit it for the first page.

        limit : typing.Optional[int]
            Maximum number of schemas to return per page (1–100; defaults to 20).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchemaPage]
            A paginated list of schemas, as a `{data, nextCursor}` envelope.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/schemas",
            method="GET",
            params={
                "userId": user_id,
                "orgId": org_id,
                "surface": surface,
                "recordType": record_type,
                "startFrom": start_from,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaPage,
                    parse_obj_as(
                        type_=SchemaPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_schema(
        self,
        *,
        type_name: str,
        display_name: str,
        allowed_surfaces: typing.Sequence[SchemaRequestAllowedSurfacesItem],
        upsert: typing.Optional[bool] = None,
        description: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[FieldDef]] = OMIT,
        lookup_fields: typing.Optional[typing.Sequence[LookupDef]] = OMIT,
        render_hints: typing.Optional[typing.Dict[str, RenderHintDef]] = OMIT,
        capabilities: typing.Optional[typing.Dict[str, bool]] = OMIT,
        index_mode: typing.Optional[SchemaRequestIndexMode] = OMIT,
        storage_profile: typing.Optional[SchemaRequestStorageProfile] = OMIT,
        active: typing.Optional[bool] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        org_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SchemaResponse]:
        """
        Defines a new record type with optional field definitions, validation rules, and lookup indexes. Idempotent by `typeName` within the same ownership scope: re-creating an existing `typeName` returns the existing schema rather than failing. The response's `created` field (and the HTTP status — 201 when created, 200 when an existing schema was returned) tells the two apart. To reconcile an existing schema to the submitted shape instead of returning it unchanged, set `?upsert=true` (this also requires the `schemas:w` scope; only legal schema changes are applied — migration-locked changes are rejected). Requires the `schemas:w` scope.

        Parameters
        ----------
        type_name : str
            Unique type identifier for this schema. Immutable after creation.

        display_name : str
            Human-readable display name for this type, shown in UIs.

        allowed_surfaces : typing.Sequence[SchemaRequestAllowedSurfacesItem]
            Which typed surfaces may bind this schema by its id: record, document, user, org, or client. Required and must be non-empty. A schema may list several surfaces (for a shared type usable on both records and documents). This drives surface-scoped schema listing (`GET /v1/schemas?surface=`) and is enforced at bind time — for example, a document cannot bind a record-only schema.

        upsert : typing.Optional[bool]
            When `true`, if a schema with the same `typeName` already exists it is reconciled to the submitted shape (additive fields, lookups, renderHints, and `active` are applied) instead of being returned unchanged; `typeName` and migration-locked lookup attributes (`rangeEnabled`/`sortBy`/`sensitive`) cannot be changed and a request to do so is rejected. A re-applied upsert whose declared shape is unchanged is a no-op (no schema-version bump). Defaults to `false`. Requires the `schemas:w` scope.

        description : typing.Optional[str]
            Optional description of what this schema is for.

        fields : typing.Optional[typing.Sequence[FieldDef]]
            Field definitions used to validate record payloads. Omit for a bare schema that performs no payload validation.

        lookup_fields : typing.Optional[typing.Sequence[LookupDef]]
            Payload fields to index for direct lookup queries. Maximum 10 lookup fields.

        render_hints : typing.Optional[typing.Dict[str, RenderHintDef]]
            UI rendering hints keyed by field id.

        capabilities : typing.Optional[typing.Dict[str, bool]]
            Feature flags for this schema. `auditHistory` (default true) controls whether a change-history (version) trail is kept for this type's data; setting it false stops recording the trail but never affects your record or document data itself. `readAccessLog` (default false; opt-in) controls accounting-of-disclosures logging: when true, each governed read of this schema's records writes a retained, subject-enumerable access record. The effective value resolves in order: this schema flag, then your context's default, then the platform default (false).

        index_mode : typing.Optional[SchemaRequestIndexMode]
            Default search-index mode for instances of this type — applies to records of this type and to documents bound to this schema, unless the individual record or document sets its own indexMode. HYBRID, SEMANTIC, and TEXT make content searchable; NONE is store-only (the data is persisted, retrievable, and usable for lookups, but not searchable). Omit for no default: a record with no indexMode of its own then defaults to NONE, and a document with no indexMode is rejected.

        storage_profile : typing.Optional[SchemaRequestStorageProfile]
            Where this type's payload is stored. STANDARD (default): payloads of 4 KB or larger are externalized to S3, smaller ones are stored inline. LOW_LATENCY: always store inline for the lowest read latency. LARGE_PAYLOAD: always externalize to S3, which lifts the 400 KB item-size ceiling. For externalized types, list and lookup responses return only the indexed projection unless you pass `includePayload=true`.

        active : typing.Optional[bool]
            Whether this schema is active. An inactive schema rejects creation of new records of its type.

        user_id : typing.Optional[str]
            Owning user — the Vectros-assigned UUID of a user in your account. Optional; omit to create an account-wide shared schema. With an API key, this sets the schema's owner explicitly. With a scoped token, the user must match the token's identity claim (if set) or fall within the token's data scope.

        org_id : typing.Optional[str]
            Owning organization — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, this sets the schema's owning organization explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        client_id : typing.Optional[str]
            Associated client — the Vectros-assigned UUID of a client in your account. Optional. With an API key, this sets the schema's client explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchemaResponse]
            A schema with the same `typeName` already existed and was returned (`created: false`) — unchanged for an idempotent create, or reconciled when `?upsert=true`.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/schemas",
            method="POST",
            params={
                "upsert": upsert,
            },
            json={
                "typeName": type_name,
                "displayName": display_name,
                "description": description,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Sequence[FieldDef], direction="write"
                ),
                "lookupFields": convert_and_respect_annotation_metadata(
                    object_=lookup_fields, annotation=typing.Sequence[LookupDef], direction="write"
                ),
                "renderHints": convert_and_respect_annotation_metadata(
                    object_=render_hints, annotation=typing.Dict[str, RenderHintDef], direction="write"
                ),
                "capabilities": capabilities,
                "indexMode": index_mode,
                "storageProfile": storage_profile,
                "allowedSurfaces": allowed_surfaces,
                "active": active,
                "userId": user_id,
                "orgId": org_id,
                "clientId": client_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaResponse,
                    parse_obj_as(
                        type_=SchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_schema(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SchemaResponse]:
        """
        Retrieves a single record schema by its id. Requires the `schemas:r` scope.

        Parameters
        ----------
        id : str
            The id of the schema to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchemaResponse]
            The requested schema.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaResponse,
                    parse_obj_as(
                        type_=SchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_schema(
        self,
        id: str,
        *,
        type_name: str,
        display_name: str,
        allowed_surfaces: typing.Sequence[SchemaRequestAllowedSurfacesItem],
        description: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[FieldDef]] = OMIT,
        lookup_fields: typing.Optional[typing.Sequence[LookupDef]] = OMIT,
        render_hints: typing.Optional[typing.Dict[str, RenderHintDef]] = OMIT,
        capabilities: typing.Optional[typing.Dict[str, bool]] = OMIT,
        index_mode: typing.Optional[SchemaRequestIndexMode] = OMIT,
        storage_profile: typing.Optional[SchemaRequestStorageProfile] = OMIT,
        active: typing.Optional[bool] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        org_id: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SchemaResponse]:
        """
        Updates a record schema. Fields you omit are preserved; `typeName` is immutable and cannot be changed. Collection fields (`fields`, `lookupFields`, `renderHints`, `capabilities`) are replaced in full when supplied. Requires the `schemas:w` scope.

        Parameters
        ----------
        id : str
            The id of the schema to update.

        type_name : str
            Unique type identifier for this schema. Immutable after creation.

        display_name : str
            Human-readable display name for this type, shown in UIs.

        allowed_surfaces : typing.Sequence[SchemaRequestAllowedSurfacesItem]
            Which typed surfaces may bind this schema by its id: record, document, user, org, or client. Required and must be non-empty. A schema may list several surfaces (for a shared type usable on both records and documents). This drives surface-scoped schema listing (`GET /v1/schemas?surface=`) and is enforced at bind time — for example, a document cannot bind a record-only schema.

        description : typing.Optional[str]
            Optional description of what this schema is for.

        fields : typing.Optional[typing.Sequence[FieldDef]]
            Field definitions used to validate record payloads. Omit for a bare schema that performs no payload validation.

        lookup_fields : typing.Optional[typing.Sequence[LookupDef]]
            Payload fields to index for direct lookup queries. Maximum 10 lookup fields.

        render_hints : typing.Optional[typing.Dict[str, RenderHintDef]]
            UI rendering hints keyed by field id.

        capabilities : typing.Optional[typing.Dict[str, bool]]
            Feature flags for this schema. `auditHistory` (default true) controls whether a change-history (version) trail is kept for this type's data; setting it false stops recording the trail but never affects your record or document data itself. `readAccessLog` (default false; opt-in) controls accounting-of-disclosures logging: when true, each governed read of this schema's records writes a retained, subject-enumerable access record. The effective value resolves in order: this schema flag, then your context's default, then the platform default (false).

        index_mode : typing.Optional[SchemaRequestIndexMode]
            Default search-index mode for instances of this type — applies to records of this type and to documents bound to this schema, unless the individual record or document sets its own indexMode. HYBRID, SEMANTIC, and TEXT make content searchable; NONE is store-only (the data is persisted, retrievable, and usable for lookups, but not searchable). Omit for no default: a record with no indexMode of its own then defaults to NONE, and a document with no indexMode is rejected.

        storage_profile : typing.Optional[SchemaRequestStorageProfile]
            Where this type's payload is stored. STANDARD (default): payloads of 4 KB or larger are externalized to S3, smaller ones are stored inline. LOW_LATENCY: always store inline for the lowest read latency. LARGE_PAYLOAD: always externalize to S3, which lifts the 400 KB item-size ceiling. For externalized types, list and lookup responses return only the indexed projection unless you pass `includePayload=true`.

        active : typing.Optional[bool]
            Whether this schema is active. An inactive schema rejects creation of new records of its type.

        user_id : typing.Optional[str]
            Owning user — the Vectros-assigned UUID of a user in your account. Optional; omit to create an account-wide shared schema. With an API key, this sets the schema's owner explicitly. With a scoped token, the user must match the token's identity claim (if set) or fall within the token's data scope.

        org_id : typing.Optional[str]
            Owning organization — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, this sets the schema's owning organization explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        client_id : typing.Optional[str]
            Associated client — the Vectros-assigned UUID of a client in your account. Optional. With an API key, this sets the schema's client explicitly. With a scoped token, it must match the token's identity claim (if set) or fall within the token's data scope.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchemaResponse]
            The updated schema.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}",
            method="PUT",
            json={
                "typeName": type_name,
                "displayName": display_name,
                "description": description,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Sequence[FieldDef], direction="write"
                ),
                "lookupFields": convert_and_respect_annotation_metadata(
                    object_=lookup_fields, annotation=typing.Sequence[LookupDef], direction="write"
                ),
                "renderHints": convert_and_respect_annotation_metadata(
                    object_=render_hints, annotation=typing.Dict[str, RenderHintDef], direction="write"
                ),
                "capabilities": capabilities,
                "indexMode": index_mode,
                "storageProfile": storage_profile,
                "allowedSurfaces": allowed_surfaces,
                "active": active,
                "userId": user_id,
                "orgId": org_id,
                "clientId": client_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchemaResponse,
                    parse_obj_as(
                        type_=SchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_schema(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Permanently deletes a record schema. The request is refused with 409 if records of this type still exist — delete those records first, since every record must reference a live schema. Requires the `schemas:w` scope.

        Parameters
        ----------
        id : str
            The id of the schema to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_schema_versions(
        self,
        id: str,
        *,
        start_from: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDataVersionPage]:
        """
        Returns the audit trail of changes to a record schema, newest first (create, update, and delete). Schema version history is always recorded — there is no per-schema toggle to disable it. Requires the `schemas:r` scope.

        Parameters
        ----------
        id : str
            The id of the schema whose version history you want.

        start_from : typing.Optional[str]
            Pagination cursor — pass the `nextCursor` value from the previous page to fetch the next one.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDataVersionPage]
            A paginated version history, as a `{data, nextCursor}` envelope.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/schemas/{encode_path_param(id)}/versions",
            method="GET",
            params={
                "startFrom": start_from,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDataVersionPage,
                    parse_obj_as(
                        type_=ModelDataVersionPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
