# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.script_page import ScriptPage
from ...types.script_response import ScriptResponse

ListScriptsResponse = typing.Union[ScriptPage, ScriptResponse]
