# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.erasure_request_response import ErasureRequestResponse
from ..types.export_request_response import ExportRequestResponse
from .raw_client import AsyncRawComplianceClient, RawComplianceClient
from .types.erasure_request_audit_disposition import ErasureRequestAuditDisposition
from .types.erasure_request_subject_type import ErasureRequestSubjectType
from .types.export_request_format import ExportRequestFormat
from .types.export_request_scope import ExportRequestScope
from .types.export_request_subject_type import ExportRequestSubjectType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ComplianceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawComplianceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawComplianceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawComplianceClient
        """
        return self._raw_client

    def create_erasure_request(
        self,
        *,
        subject_type: ErasureRequestSubjectType,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        audit_disposition: typing.Optional[ErasureRequestAuditDisposition] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ErasureRequestResponse:
        """
        Submits a right-to-erasure request for a single end-subject (a user, client, or organization). Erasure removes exactly the data the subject solely owns across the declared contexts, plus the subject's identity and lookup rows. It never touches another account's data and never cascades into another subject's data. The request is asynchronous: it returns 202 with a `requestId`; poll `GET /v1/erasure-requests/{id}` until the job completes to obtain the completion certificate. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        subject_type : ErasureRequestSubjectType
            The kind of end-subject to erase: `user`, `client`, or `org`.

        subject_id : typing.Optional[str]
            The platform id of the subject to erase (the userId, clientId, or orgId returned when the subject was created). Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId`. Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts in which to erase the subject. As the data controller, you declare the blast radius: each listed context is erased independently and reported separately on the certificate. Omit or leave empty to erase every context the subject has data in; those contexts are then enumerated and erased one at a time, never as a single account-wide sweep. Any context you do not list is left untouched, and managing that residual data is your responsibility.

        audit_disposition : typing.Optional[ErasureRequestAuditDisposition]
            How to handle the subject's audit and version-history trail. This governs only the audit data — the subject's records and documents are always erased regardless. `retain-redacted` (the default) keeps the compliance audit trail with sensitive data redacted; `purge` additionally hard-removes the audit history itself (subject to your legal obligations).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ErasureRequestResponse
            Erasure request accepted. The body carries the request id and initial status; poll the GET endpoint for the certificate.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.compliance.create_erasure_request(
            subject_type="user",
        )
        """
        _response = self._raw_client.create_erasure_request(
            subject_type=subject_type,
            subject_id=subject_id,
            external_id=external_id,
            context_scope=context_scope,
            audit_disposition=audit_disposition,
            request_options=request_options,
        )
        return _response.data

    def get_erasure_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ErasureRequestResponse:
        """
        Polls an erasure request by id. While the job is still running this returns its status only; once it completes, the response also includes the verifiable completion certificate (which contexts were swept, per-context deletion counts, and reports of dangling references and shared rows that were left intact). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the erasure request to poll, as returned when the request was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ErasureRequestResponse
            The current status of the erasure request, plus the completion certificate once it has finished.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.compliance.get_erasure_request(
            id="er_550e8400e29b41d4a716446655440000",
        )
        """
        _response = self._raw_client.get_erasure_request(id, request_options=request_options)
        return _response.data

    def create_export(
        self,
        *,
        scope: typing.Optional[ExportRequestScope] = OMIT,
        subject_type: typing.Optional[ExportRequestSubjectType] = OMIT,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        format: typing.Optional[ExportRequestFormat] = OMIT,
        include_audit_history: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExportRequestResponse:
        """
        Submits an asynchronous job to export your account's data, or a single end-subject's data, across the requested contexts. The request returns 202 with an `exportJobId`; poll `GET /v1/admin/export/{id}` until the job completes to obtain a short-lived presigned download URL and a manifest describing the payload. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        scope : typing.Optional[ExportRequestScope]
            What to export. `tenant` (the default) exports all of your account's data across the requested contexts; `subject` exports a single end-subject's data (for example, to satisfy a one-person data-portability request). Additional scopes may be added in the future.

        subject_type : typing.Optional[ExportRequestSubjectType]
            The kind of subject to export: `user`, `client`, or `org`. Required only when `scope` is `subject`.

        subject_id : typing.Optional[str]
            The platform id of the subject to export. Used only when `scope` is `subject`. Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId` (only when `scope` is `subject`). Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts to export. Omit or leave empty to export all of your contexts. Each listed context is exported and reported separately in the manifest.

        format : typing.Optional[ExportRequestFormat]
            Serialization format of the export payload. NDJSON (newline-delimited JSON, one row per line) is currently the only supported format; more may be added in the future. The manifest carries a `formatVersion` so you can parse the payload in a forward-compatible way.

        include_audit_history : typing.Optional[bool]
            Whether to also include the audit and version-history trail of the exported data, not just the current live rows. Defaults to false (live data only). Set true to also export the retained version history. This governs only the audit data — the live records are always included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportRequestResponse
            Export job accepted. The body carries the job id and initial status; poll the GET endpoint for the result.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.compliance.create_export()
        """
        _response = self._raw_client.create_export(
            scope=scope,
            subject_type=subject_type,
            subject_id=subject_id,
            external_id=external_id,
            context_scope=context_scope,
            format=format,
            include_audit_history=include_audit_history,
            request_options=request_options,
        )
        return _response.data

    def get_export(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ExportRequestResponse:
        """
        Polls an export job by id. While the job is still running this returns its status only; once it completes, the response also includes a short-lived presigned download URL and a manifest (format version and per-context counts). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the export job to poll, as returned when the job was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportRequestResponse
            The current status of the export job, plus the download URL and manifest once it has completed.

        Examples
        --------
        from vectros import VectrosApi

        client = VectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.compliance.get_export(
            id="exp_550e8400e29b41d4a716446655440000",
        )
        """
        _response = self._raw_client.get_export(id, request_options=request_options)
        return _response.data


class AsyncComplianceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawComplianceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawComplianceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawComplianceClient
        """
        return self._raw_client

    async def create_erasure_request(
        self,
        *,
        subject_type: ErasureRequestSubjectType,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        audit_disposition: typing.Optional[ErasureRequestAuditDisposition] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ErasureRequestResponse:
        """
        Submits a right-to-erasure request for a single end-subject (a user, client, or organization). Erasure removes exactly the data the subject solely owns across the declared contexts, plus the subject's identity and lookup rows. It never touches another account's data and never cascades into another subject's data. The request is asynchronous: it returns 202 with a `requestId`; poll `GET /v1/erasure-requests/{id}` until the job completes to obtain the completion certificate. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        subject_type : ErasureRequestSubjectType
            The kind of end-subject to erase: `user`, `client`, or `org`.

        subject_id : typing.Optional[str]
            The platform id of the subject to erase (the userId, clientId, or orgId returned when the subject was created). Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId`. Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts in which to erase the subject. As the data controller, you declare the blast radius: each listed context is erased independently and reported separately on the certificate. Omit or leave empty to erase every context the subject has data in; those contexts are then enumerated and erased one at a time, never as a single account-wide sweep. Any context you do not list is left untouched, and managing that residual data is your responsibility.

        audit_disposition : typing.Optional[ErasureRequestAuditDisposition]
            How to handle the subject's audit and version-history trail. This governs only the audit data — the subject's records and documents are always erased regardless. `retain-redacted` (the default) keeps the compliance audit trail with sensitive data redacted; `purge` additionally hard-removes the audit history itself (subject to your legal obligations).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ErasureRequestResponse
            Erasure request accepted. The body carries the request id and initial status; poll the GET endpoint for the certificate.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.compliance.create_erasure_request(
                subject_type="user",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_erasure_request(
            subject_type=subject_type,
            subject_id=subject_id,
            external_id=external_id,
            context_scope=context_scope,
            audit_disposition=audit_disposition,
            request_options=request_options,
        )
        return _response.data

    async def get_erasure_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ErasureRequestResponse:
        """
        Polls an erasure request by id. While the job is still running this returns its status only; once it completes, the response also includes the verifiable completion certificate (which contexts were swept, per-context deletion counts, and reports of dangling references and shared rows that were left intact). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the erasure request to poll, as returned when the request was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ErasureRequestResponse
            The current status of the erasure request, plus the completion certificate once it has finished.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.compliance.get_erasure_request(
                id="er_550e8400e29b41d4a716446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_erasure_request(id, request_options=request_options)
        return _response.data

    async def create_export(
        self,
        *,
        scope: typing.Optional[ExportRequestScope] = OMIT,
        subject_type: typing.Optional[ExportRequestSubjectType] = OMIT,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        format: typing.Optional[ExportRequestFormat] = OMIT,
        include_audit_history: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExportRequestResponse:
        """
        Submits an asynchronous job to export your account's data, or a single end-subject's data, across the requested contexts. The request returns 202 with an `exportJobId`; poll `GET /v1/admin/export/{id}` until the job completes to obtain a short-lived presigned download URL and a manifest describing the payload. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        scope : typing.Optional[ExportRequestScope]
            What to export. `tenant` (the default) exports all of your account's data across the requested contexts; `subject` exports a single end-subject's data (for example, to satisfy a one-person data-portability request). Additional scopes may be added in the future.

        subject_type : typing.Optional[ExportRequestSubjectType]
            The kind of subject to export: `user`, `client`, or `org`. Required only when `scope` is `subject`.

        subject_id : typing.Optional[str]
            The platform id of the subject to export. Used only when `scope` is `subject`. Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId` (only when `scope` is `subject`). Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts to export. Omit or leave empty to export all of your contexts. Each listed context is exported and reported separately in the manifest.

        format : typing.Optional[ExportRequestFormat]
            Serialization format of the export payload. NDJSON (newline-delimited JSON, one row per line) is currently the only supported format; more may be added in the future. The manifest carries a `formatVersion` so you can parse the payload in a forward-compatible way.

        include_audit_history : typing.Optional[bool]
            Whether to also include the audit and version-history trail of the exported data, not just the current live rows. Defaults to false (live data only). Set true to also export the retained version history. This governs only the audit data — the live records are always included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportRequestResponse
            Export job accepted. The body carries the job id and initial status; poll the GET endpoint for the result.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.compliance.create_export()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_export(
            scope=scope,
            subject_type=subject_type,
            subject_id=subject_id,
            external_id=external_id,
            context_scope=context_scope,
            format=format,
            include_audit_history=include_audit_history,
            request_options=request_options,
        )
        return _response.data

    async def get_export(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExportRequestResponse:
        """
        Polls an export job by id. While the job is still running this returns its status only; once it completes, the response also includes a short-lived presigned download URL and a manifest (format version and per-context counts). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the export job to poll, as returned when the job was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportRequestResponse
            The current status of the export job, plus the download URL and manifest once it has completed.

        Examples
        --------
        import asyncio

        from vectros import AsyncVectrosApi

        client = AsyncVectrosApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.compliance.get_export(
                id="exp_550e8400e29b41d4a716446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_export(id, request_options=request_options)
        return _response.data
