# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.not_implemented_error import NotImplementedError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..types.erasure_request_response import ErasureRequestResponse
from ..types.export_request_response import ExportRequestResponse
from .types.erasure_request_audit_disposition import ErasureRequestAuditDisposition
from .types.export_request_format import ExportRequestFormat
from .types.export_request_scope import ExportRequestScope
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawComplianceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_erasure_request(
        self,
        *,
        subject_type: str,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        audit_disposition: typing.Optional[ErasureRequestAuditDisposition] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ErasureRequestResponse]:
        """
        Submits an erasure request for a single end-subject (a user, or an identity entity in any namespace). Erasure deletes the records, documents, folders and record schemas the subject solely owns across the declared contexts (and, for a user, its access profiles there), plus its identity and lookup rows when all contexts are covered. Rows co-owned with another owner scope or principal are kept; read-access log entries are not erased. The request is asynchronous: it returns 202 with a `requestId`; poll `GET /v1/erasure-requests/{id}` until the job completes to obtain the completion certificate. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        subject_type : str
            The kind of end-subject to erase: `user` for a person, or an ownership namespace such as `org` or `client` — including a custom namespace you have defined.

        subject_id : typing.Optional[str]
            The platform id of the subject to erase (the Vectros-assigned id returned when the subject was created). Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId`. Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts in which to erase the subject. As the data controller, you declare the blast radius: each listed context is erased independently and reported separately on the certificate. Omit or leave empty to erase in every context of your account: every context is swept, whether or not the subject holds data in it. Any context you do not list is left untouched, including the subject's access grants there, and managing that residual data is your responsibility. Every listed context must exist in your account: a `contextScope` that names a context that does not exist is rejected with 400 before anything is erased. A row in a listed context that is co-owned with another owner scope or principal is kept, not erased, and counted as `sharedRowsSkipped`. The subject's identity (its user or entity record) is account-wide rather than per-context, so it is deleted only when the request covers every context of your account, by omitting `contextScope` or by listing them all; the one exception is an entity that belongs to a single context (a context-owned namespace), which is deleted when that context is listed. A request that lists only some contexts leaves the identity in place and sets `identityRetained` on the certificate, so you can send further requests for the remaining contexts; send one without `contextScope` to finish and delete the identity.

        audit_disposition : typing.Optional[ErasureRequestAuditDisposition]
            How to handle the subject's audit and version-history trail. This governs only the audit data — the subject's records and documents are always erased regardless. `retain-redacted` (the default) keeps the compliance audit trail with sensitive data redacted. `purge` additionally hard-removes the audit history of the rows this request erased, including the subject's own identity history and the audit payloads stored outside the database for those rows. `purge` is supported only for subject types `user`, `org` and `client` — a request for any other subject type is rejected with 400 — and it never removes the history of a row that was retained because another principal also owns it. `purge` finds history through the owner each version carried when it was written, so it is a primitive, not a completeness guarantee: versions written while a row belonged to a different owner are not found, and the history of an already-deleted row that another owner shared is removed together with the erased owner's. Stored audit payloads are deleted asynchronously: the request completes once the audit records are removed, and the payloads follow shortly after; a payload delete that cannot complete is retried and raised to Vectros operations, so `completed` does not by itself prove every payload is already gone. `purge` is subject to your own legal-retention obligations; it does not consult a retention setting.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ErasureRequestResponse]
            Erasure request accepted. The body carries the request id and initial status; poll the GET endpoint for the certificate.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/erasure-requests",
            method="POST",
            json={
                "subjectType": subject_type,
                "subjectId": subject_id,
                "externalId": external_id,
                "contextScope": context_scope,
                "auditDisposition": audit_disposition,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ErasureRequestResponse,
                    parse_obj_as(
                        type_=ErasureRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_erasure_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ErasureRequestResponse]:
        """
        Polls an erasure request by id. While the job is still running this returns its status only; once it completes, the response also includes the completion certificate (which contexts were swept, per-context deletion counts, whether the identity was kept, and reports of dangling references and shared rows left intact). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the erasure request to poll, as returned when the request was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ErasureRequestResponse]
            The current status of the erasure request, plus the completion certificate once it has finished.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/erasure-requests/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ErasureRequestResponse,
                    parse_obj_as(
                        type_=ErasureRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_export(
        self,
        *,
        scope: typing.Optional[ExportRequestScope] = OMIT,
        subject_type: typing.Optional[str] = OMIT,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        format: typing.Optional[ExportRequestFormat] = OMIT,
        include_audit_history: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ExportRequestResponse]:
        """
        Submits an asynchronous job to export your account's data, or a single end-subject's data, across the requested contexts. The request returns 202 with an `exportJobId`; poll `GET /v1/admin/export/{id}` until the job completes to obtain a short-lived presigned download URL and a manifest describing the payload. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        scope : typing.Optional[ExportRequestScope]
            What to export. `tenant` (the default) exports all of your account's data across the requested contexts; `subject` exports a single end-subject's data (for example, to satisfy a one-person data-portability request). Additional scopes may be added in the future.

        subject_type : typing.Optional[str]
            The kind of subject to export: `user` for a person, or an ownership namespace such as `org` or `client` — including a custom namespace you have defined. Required only when `scope` is `subject`.

        subject_id : typing.Optional[str]
            The platform id of the subject to export. Used only when `scope` is `subject`. Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId` (only when `scope` is `subject`). Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts to export. Omit or leave empty to export all of your contexts. Each listed context is exported and reported separately in the manifest.

        format : typing.Optional[ExportRequestFormat]
            Serialization format of the export payload. NDJSON (newline-delimited JSON, one row per line) is currently the only supported format; more may be added in the future. The manifest carries a `formatVersion` so you can parse the payload in a forward-compatible way.

        include_audit_history : typing.Optional[bool]
            Whether to also include the audit and version-history trail of the exported data, not just the current live rows. Defaults to false (live data only). Set true to also export the retained version history. This governs only the audit data — the live records are always included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExportRequestResponse]
            Export job accepted. The body carries the job id and initial status; poll the GET endpoint for the result.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/admin/export",
            method="POST",
            json={
                "scope": scope,
                "subjectType": subject_type,
                "subjectId": subject_id,
                "externalId": external_id,
                "contextScope": context_scope,
                "format": format,
                "includeAuditHistory": include_audit_history,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExportRequestResponse,
                    parse_obj_as(
                        type_=ExportRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_export(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ExportRequestResponse]:
        """
        Polls an export job by id. While the job is still running this returns its status only; once it completes, the response also includes a short-lived presigned download URL and a manifest (format version and per-context counts). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the export job to poll, as returned when the job was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExportRequestResponse]
            The current status of the export job, plus the download URL and manifest once it has completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/admin/export/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExportRequestResponse,
                    parse_obj_as(
                        type_=ExportRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawComplianceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_erasure_request(
        self,
        *,
        subject_type: str,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        audit_disposition: typing.Optional[ErasureRequestAuditDisposition] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ErasureRequestResponse]:
        """
        Submits an erasure request for a single end-subject (a user, or an identity entity in any namespace). Erasure deletes the records, documents, folders and record schemas the subject solely owns across the declared contexts (and, for a user, its access profiles there), plus its identity and lookup rows when all contexts are covered. Rows co-owned with another owner scope or principal are kept; read-access log entries are not erased. The request is asynchronous: it returns 202 with a `requestId`; poll `GET /v1/erasure-requests/{id}` until the job completes to obtain the completion certificate. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        subject_type : str
            The kind of end-subject to erase: `user` for a person, or an ownership namespace such as `org` or `client` — including a custom namespace you have defined.

        subject_id : typing.Optional[str]
            The platform id of the subject to erase (the Vectros-assigned id returned when the subject was created). Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId`. Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts in which to erase the subject. As the data controller, you declare the blast radius: each listed context is erased independently and reported separately on the certificate. Omit or leave empty to erase in every context of your account: every context is swept, whether or not the subject holds data in it. Any context you do not list is left untouched, including the subject's access grants there, and managing that residual data is your responsibility. Every listed context must exist in your account: a `contextScope` that names a context that does not exist is rejected with 400 before anything is erased. A row in a listed context that is co-owned with another owner scope or principal is kept, not erased, and counted as `sharedRowsSkipped`. The subject's identity (its user or entity record) is account-wide rather than per-context, so it is deleted only when the request covers every context of your account, by omitting `contextScope` or by listing them all; the one exception is an entity that belongs to a single context (a context-owned namespace), which is deleted when that context is listed. A request that lists only some contexts leaves the identity in place and sets `identityRetained` on the certificate, so you can send further requests for the remaining contexts; send one without `contextScope` to finish and delete the identity.

        audit_disposition : typing.Optional[ErasureRequestAuditDisposition]
            How to handle the subject's audit and version-history trail. This governs only the audit data — the subject's records and documents are always erased regardless. `retain-redacted` (the default) keeps the compliance audit trail with sensitive data redacted. `purge` additionally hard-removes the audit history of the rows this request erased, including the subject's own identity history and the audit payloads stored outside the database for those rows. `purge` is supported only for subject types `user`, `org` and `client` — a request for any other subject type is rejected with 400 — and it never removes the history of a row that was retained because another principal also owns it. `purge` finds history through the owner each version carried when it was written, so it is a primitive, not a completeness guarantee: versions written while a row belonged to a different owner are not found, and the history of an already-deleted row that another owner shared is removed together with the erased owner's. Stored audit payloads are deleted asynchronously: the request completes once the audit records are removed, and the payloads follow shortly after; a payload delete that cannot complete is retried and raised to Vectros operations, so `completed` does not by itself prove every payload is already gone. `purge` is subject to your own legal-retention obligations; it does not consult a retention setting.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ErasureRequestResponse]
            Erasure request accepted. The body carries the request id and initial status; poll the GET endpoint for the certificate.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/erasure-requests",
            method="POST",
            json={
                "subjectType": subject_type,
                "subjectId": subject_id,
                "externalId": external_id,
                "contextScope": context_scope,
                "auditDisposition": audit_disposition,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ErasureRequestResponse,
                    parse_obj_as(
                        type_=ErasureRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_erasure_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ErasureRequestResponse]:
        """
        Polls an erasure request by id. While the job is still running this returns its status only; once it completes, the response also includes the completion certificate (which contexts were swept, per-context deletion counts, whether the identity was kept, and reports of dangling references and shared rows left intact). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the erasure request to poll, as returned when the request was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ErasureRequestResponse]
            The current status of the erasure request, plus the completion certificate once it has finished.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/erasure-requests/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ErasureRequestResponse,
                    parse_obj_as(
                        type_=ErasureRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_export(
        self,
        *,
        scope: typing.Optional[ExportRequestScope] = OMIT,
        subject_type: typing.Optional[str] = OMIT,
        subject_id: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        context_scope: typing.Optional[typing.Sequence[str]] = OMIT,
        format: typing.Optional[ExportRequestFormat] = OMIT,
        include_audit_history: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ExportRequestResponse]:
        """
        Submits an asynchronous job to export your account's data, or a single end-subject's data, across the requested contexts. The request returns 202 with an `exportJobId`; poll `GET /v1/admin/export/{id}` until the job completes to obtain a short-lived presigned download URL and a manifest describing the payload. Requires a root API key — a scoped credential is rejected with 403.

        Parameters
        ----------
        scope : typing.Optional[ExportRequestScope]
            What to export. `tenant` (the default) exports all of your account's data across the requested contexts; `subject` exports a single end-subject's data (for example, to satisfy a one-person data-portability request). Additional scopes may be added in the future.

        subject_type : typing.Optional[str]
            The kind of subject to export: `user` for a person, or an ownership namespace such as `org` or `client` — including a custom namespace you have defined. Required only when `scope` is `subject`.

        subject_id : typing.Optional[str]
            The platform id of the subject to export. Used only when `scope` is `subject`. Provide exactly one of `subjectId` or `externalId`.

        external_id : typing.Optional[str]
            Your own externalId for the subject, as an alternative to `subjectId` (only when `scope` is `subject`). Provide exactly one of `subjectId` or `externalId`.

        context_scope : typing.Optional[typing.Sequence[str]]
            The contexts to export. Omit or leave empty to export all of your contexts. Each listed context is exported and reported separately in the manifest.

        format : typing.Optional[ExportRequestFormat]
            Serialization format of the export payload. NDJSON (newline-delimited JSON, one row per line) is currently the only supported format; more may be added in the future. The manifest carries a `formatVersion` so you can parse the payload in a forward-compatible way.

        include_audit_history : typing.Optional[bool]
            Whether to also include the audit and version-history trail of the exported data, not just the current live rows. Defaults to false (live data only). Set true to also export the retained version history. This governs only the audit data — the live records are always included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExportRequestResponse]
            Export job accepted. The body carries the job id and initial status; poll the GET endpoint for the result.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/admin/export",
            method="POST",
            json={
                "scope": scope,
                "subjectType": subject_type,
                "subjectId": subject_id,
                "externalId": external_id,
                "contextScope": context_scope,
                "format": format,
                "includeAuditHistory": include_audit_history,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExportRequestResponse,
                    parse_obj_as(
                        type_=ExportRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_export(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ExportRequestResponse]:
        """
        Polls an export job by id. While the job is still running this returns its status only; once it completes, the response also includes a short-lived presigned download URL and a manifest (format version and per-context counts). Requires a root API key.

        Parameters
        ----------
        id : str
            The id of the export job to poll, as returned when the job was submitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExportRequestResponse]
            The current status of the export job, plus the download URL and manifest once it has completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/admin/export/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExportRequestResponse,
                    parse_obj_as(
                        type_=ExportRequestResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
