# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .app_context_response_status import AppContextResponseStatus


class AppContextResponse(UniversalBaseModel):
    """
    An app context: a namespace you define to group access profiles and roles for one of your applications.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque composite identifier for this app context. Use it as the pagination cursor (pass it as `startFrom` to page through results); for everything else, refer to the app context by its `contextId`.
    """

    context_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contextId"),
        pydantic.Field(alias="contextId", description="Your identifier for the app context."),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable display name for the app context.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text description of the app context.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="When the app context was created, as an ISO-8601 UTC timestamp."
        ),
    ] = None
    last_modified: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastModified"),
        pydantic.Field(
            alias="lastModified", description="When the app context was last modified, as an ISO-8601 UTC timestamp."
        ),
    ] = None
    status: typing.Optional[AppContextResponseStatus] = pydantic.Field(default=None)
    """
    Lifecycle status of the app context: `active` under normal operation; `purging` while an asynchronous delete is draining the context's data; `deleted` once that teardown completes. After you call DELETE on an app context (which returns 202 and drains asynchronously), poll this field to observe when the teardown has finished.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
