# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .app_context_response_status import AppContextResponseStatus


class AppContextResponse(UniversalBaseModel):
    """
    An app context: a namespace you define to group access profiles and roles for one of your applications.
    """

    created: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this call created a new app context. True when a new app context was created; false when an app context with the same `contextId` already existed and was returned unchanged (idempotent create) or updated (when `?upsert=true`). Present only on the create response (POST /v1/app-contexts); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing app context was returned.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque composite identifier for this app context. Use it as the pagination cursor (pass it as `startFrom` to page through results); for everything else, refer to the app context by its `contextId`.
    """

    context_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contextId"),
        pydantic.Field(alias="contextId", description="Your identifier for the app context."),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable display name for the app context.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text description of the app context.
    """

    company_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="companyName"),
        pydantic.Field(
            alias="companyName",
            description="Display name for the organization deploying this app context, or absent if unset. Distinct from `name` (the app's own identity) — used to personalize platform-sent correspondence (e.g. sub-user invitation emails) with your own branding.",
        ),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="When the app context was created, as an ISO-8601 UTC timestamp."
        ),
    ] = None
    last_modified: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastModified"),
        pydantic.Field(
            alias="lastModified", description="When the app context was last modified, as an ISO-8601 UTC timestamp."
        ),
    ] = None
    status: typing.Optional[AppContextResponseStatus] = pydantic.Field(default=None)
    """
    Lifecycle status of the app context: `active` under normal operation; `purging` while an asynchronous delete is draining the context's data; `deleted` once that teardown completes. After you call DELETE on an app context (which returns 202 and drains asynchronously), poll this field to observe when the teardown has finished.
    """

    metering_axis: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="meteringAxis"),
        pydantic.Field(
            alias="meteringAxis",
            description="The declared per-principal metering axis for this app context, or absent if unset (context-only accounting).",
        ),
    ] = None
    principal_burst_limit: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="principalBurstLimit"),
        pydantic.Field(
            alias="principalBurstLimit",
            description="Per-principal, per-minute request cap for the opt-in per-principal burst-protection feature, or absent if unset.",
        ),
    ] = None
    principal_usage_cap: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="principalUsageCap"),
        pydantic.Field(
            alias="principalUsageCap",
            description="Per-principal, per-billing-period operation cap for the opt-in per-principal usage/quota feature, or absent if unset (usage is still tracked for visibility/billing without a cap when `meteringAxis` is set but this is absent).",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
