# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BatchLookupInput(UniversalBaseModel):
    """
    A single equality lookup within a batch-lookup request: find the records of a given type whose lookup field exactly matches a value.
    """

    ref: typing.Optional[str] = pydantic.Field(default=None)
    """
    Your correlation id for this lookup, echoed back on the matching result group so you can pair results to inputs regardless of ordering.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The record type to look up.
    """

    field: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the lookup field to match on, as declared on the record schema.
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    The exact value to match against the lookup field.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
