# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .content_delta_event_event import ContentDeltaEventEvent
from .done_event_event import DoneEventEvent
from .error_event_event import ErrorEventEvent


class ChatStreamEvent_ContentDelta(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/chat`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["content_delta"] = "content_delta"
    event: ContentDeltaEventEvent
    delta: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ChatStreamEvent_Done(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/chat`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["done"] = "done"
    event: DoneEventEvent
    input_tokens: typing_extensions.Annotated[
        int, FieldMetadata(alias="inputTokens"), pydantic.Field(alias="inputTokens")
    ]
    output_tokens: typing_extensions.Annotated[
        int, FieldMetadata(alias="outputTokens"), pydantic.Field(alias="outputTokens")
    ]
    model: str
    platform_credits_charged: typing_extensions.Annotated[
        float, FieldMetadata(alias="platformCreditsCharged"), pydantic.Field(alias="platformCreditsCharged")
    ]
    inference_balance_cents_charged: typing_extensions.Annotated[
        int, FieldMetadata(alias="inferenceBalanceCentsCharged"), pydantic.Field(alias="inferenceBalanceCentsCharged")
    ]
    cache_read_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="cacheReadTokens"), pydantic.Field(alias="cacheReadTokens")
    ] = None
    cache_create_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="cacheCreateTokens"), pydantic.Field(alias="cacheCreateTokens")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ChatStreamEvent_Error(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/chat`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["error"] = "error"
    event: ErrorEventEvent
    message: str
    code: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ChatStreamEvent = typing_extensions.Annotated[
    typing.Union[ChatStreamEvent_ContentDelta, ChatStreamEvent_Done, ChatStreamEvent_Error],
    pydantic.Field(discriminator="type"),
]
