# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .content_delta_event_event import ContentDeltaEventEvent


class ContentDeltaEvent(UniversalBaseModel):
    """
    A streamed chunk of generated model output. Concatenate the `delta` values in arrival order to reconstruct the full response.
    """

    event: ContentDeltaEventEvent = pydantic.Field()
    """
    Backward-compatible alias of `type`. Always `content_delta`.
    """

    delta: str = pydantic.Field()
    """
    The next chunk of generated text.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
