# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .document_context_event_event import DocumentContextEventEvent


class DocumentContextEvent(UniversalBaseModel):
    """
    Emitted by `POST /v1/documents/{id}/ask` before the first `content_delta`, describing the document loaded as context.
    """

    event: DocumentContextEventEvent = pydantic.Field()
    """
    Backward-compatible alias of `type`. Always `document_context`.
    """

    document_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="documentId"),
        pydantic.Field(
            alias="documentId", description="The identifier of the document whose text was loaded as context."
        ),
    ]
    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The display title you supplied for the document, if any.
    """

    text_bytes: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="textBytes"),
        pydantic.Field(alias="textBytes", description="The size of the extracted document text, in bytes."),
    ]
    model: str = pydantic.Field()
    """
    The model alias used to answer this request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
