# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DocumentDownloadResponse(UniversalBaseModel):
    """
    Presigned download URL for a file-backed document.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Document ID.
    """

    download_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="downloadUrl"),
        pydantic.Field(
            alias="downloadUrl",
            description="Presigned download URL for the original file. Short-lived — fetch the file before the time given in `expires`.",
        ),
    ] = None
    expires: typing.Optional[int] = pydantic.Field(default=None)
    """
    Epoch-millis (Unix milliseconds) timestamp at which the presigned URL expires.
    """

    file_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="fileType"),
        pydantic.Field(alias="fileType", description="MIME type of the file, as captured at upload time."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
