# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .done_event_event import DoneEventEvent


class DoneEvent(UniversalBaseModel):
    """
    Terminal event emitted after the model finishes or the stream ends cleanly. Reports total token usage and the billing breakdown for this call.
    """

    event: DoneEventEvent = pydantic.Field()
    """
    Backward-compatible alias of `type`. Always `done`.
    """

    input_tokens: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="inputTokens"),
        pydantic.Field(
            alias="inputTokens",
            description="Total input tokens consumed by the model, including the system prompt and all messages.",
        ),
    ]
    output_tokens: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="outputTokens"),
        pydantic.Field(alias="outputTokens", description="Total output tokens generated by the model."),
    ]
    model: str = pydantic.Field()
    """
    The model alias used for this call.
    """

    platform_credits_charged: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="platformCreditsCharged"),
        pydantic.Field(
            alias="platformCreditsCharged",
            description="Credits debited from your monthly plan allowance for this call's per-call platform overhead. One credit equals one cent.",
        ),
    ]
    inference_balance_cents_charged: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="inferenceBalanceCentsCharged"),
        pydantic.Field(
            alias="inferenceBalanceCentsCharged",
            description="Cents debited from your pre-paid inference balance for the model's token cost.",
        ),
    ]
    cache_read_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="cacheReadTokens"),
        pydantic.Field(
            alias="cacheReadTokens",
            description="Number of input tokens served from the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.",
        ),
    ] = None
    cache_create_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="cacheCreateTokens"),
        pydantic.Field(
            alias="cacheCreateTokens",
            description="Number of tokens written to the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
