# This file was auto-generated by Fern from our API Definition.

import typing

ExportRequestResponseStatus = typing.Union[typing.Literal["accepted", "processing", "completed", "failed"], typing.Any]
