# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FolderResponse(UniversalBaseModel):
    """
    A folder used to organize your documents and records.
    """

    created: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Present only on a create response: `true` when a new folder was created (HTTP 201), `false` when a folder with the same slug already existed under the same parent and was returned instead (HTTP 200). Omitted on reads, lists, and updates.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the folder, assigned by Vectros.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable display name of the folder.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional description of the folder's contents or purpose.
    """

    parent_folder_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="parentFolderId"),
        pydantic.Field(
            alias="parentFolderId", description="ID of this folder's parent. Null when the folder is a root folder."
        ),
    ] = None
    slug: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable URL-safe slug for the folder, unique among its siblings under the same parent. Assigned at creation and immutable thereafter.
    """

    depth: typing.Optional[int] = pydantic.Field(default=None)
    """
    How deeply the folder is nested. A root folder has depth 0; each level below increments by 1.
    """

    is_protected: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isProtected"),
        pydantic.Field(
            alias="isProtected",
            description="Whether this folder is protected from deletion. Your context's root folder is protected.",
        ),
    ] = None
    user_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="userId"),
        pydantic.Field(
            alias="userId",
            description="ID of the user that owns this folder — the Vectros-assigned UUID of a user in your account. Null if the folder is not owned by a specific user.",
        ),
    ] = None
    scopes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The folder's scope ownership as canonical `namespace:value` entries (at most 2). `org` and `client` are reserved namespace names; any other is one you registered yourself. Set at creation, either explicitly or automatically from the calling token's identity. Empty for a folder owned by a user alone (or unowned).
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the folder was created, as an ISO-8601 UTC timestamp."),
    ] = None
    last_modified: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastModified"),
        pydantic.Field(
            alias="lastModified", description="When the folder was last modified, as an ISO-8601 UTC timestamp."
        ),
    ] = None
    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Optimistic-concurrency version, incremented on every successful write. Pass it back as `expectedVersion` on a later update or patch to avoid silently overwriting a concurrent change — the write is rejected with a 409 version conflict if the folder has changed since.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
