# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .index_failure_code import IndexFailureCode


class IndexFailure(UniversalBaseModel):
    """
    Why search indexing failed. Present only when the index status is FAILED.
    """

    code: typing.Optional[IndexFailureCode] = pydantic.Field(default=None)
    """
    A stable, machine-readable reason code. Branch on this value rather than on `message`. `SOURCE_UNAVAILABLE` — the underlying item could not be loaded and may have been deleted. `TEXT_INDEX_FAILED` — keyword indexing failed; the content may still be findable by semantic search. `EMBEDDING_FAILED` — semantic indexing failed; the content may still be findable by keyword search. `INDEXING_FAILED` — no index leg is serving this content, so it is not findable by search at all. `VECTOR_LIMIT_EXCEEDED` — your vector storage limit was reached, so semantic indexing was skipped; keyword search is still serving this content. `INTERNAL` — an error on our side; retry, and contact support if it persists.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    A human-readable explanation of the failure, suitable for showing to an end user. Wording may change between releases — branch on `code` instead.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
