# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class IngestEntry(UniversalBaseModel):
    """
    Ingest count, bytes, and credits for a single mode
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of ingest operations
    """

    bytes: typing.Optional[int] = pydantic.Field(default=None)
    """
    Bytes ingested
    """

    credits: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits charged for these ingests (rounded down)
    """

    credits_milli: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="creditsMilli"),
        pydantic.Field(alias="creditsMilli", description="credits in milli-credit precision (exact)"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
