# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .self_signup_policy import SelfSignupPolicy


class IssuerResponse(UniversalBaseModel):
    """
    A registered trusted third-party IdP issuer.
    """

    issuer_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="issuerId"),
        pydantic.Field(alias="issuerId", description="This issuer's slug within your tenant."),
    ] = None
    issuer: typing.Optional[str] = pydantic.Field(default=None)
    """
    The IdP's `iss` claim value.
    """

    jwks_uri: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="jwksUri"),
        pydantic.Field(alias="jwksUri", description="The IdP's remote JWKS endpoint."),
    ] = None
    audience: typing.Optional[str] = pydantic.Field(default=None)
    """
    The required `aud` claim value.
    """

    context_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contextId"),
        pydantic.Field(alias="contextId", description="The app context an exchanged token targets."),
    ] = None
    sub_claim: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="subClaim"),
        pydantic.Field(alias="subClaim", description="The subject-identifier claim."),
    ] = None
    email_claim: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="emailClaim"),
        pydantic.Field(alias="emailClaim", description="The subject-email claim."),
    ] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    `active` or `suspended`. A suspended issuer is registered but its tokens are no longer accepted for exchange.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="Timestamp when the issuer was registered, as an ISO-8601 UTC timestamp."
        ),
    ] = None
    created: typing.Optional[bool] = pydantic.Field(default=None)
    """
    `true` if this call registered a new issuer, `false` if issuerId already existed in your tenant and the existing registration was returned unchanged. Only present on the create response (POST /v1/auth/issuers); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing registration was returned.
    """

    self_signup_policies: typing_extensions.Annotated[
        typing.Optional[typing.List[SelfSignupPolicy]],
        FieldMetadata(alias="selfSignupPolicies"),
        pydantic.Field(
            alias="selfSignupPolicies",
            description="Configured self-service signup policies, if any. Absent (not an empty list) when self-signup is not configured for this issuer.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
