# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Jwk(UniversalBaseModel):
    """
    A single JSON Web Key entry. Currently an EC key on the P-256 curve.
    """

    kty: typing.Optional[str] = pydantic.Field(default=None)
    """
    Key type. Always `EC` for this P-256 key.
    """

    crv: typing.Optional[str] = pydantic.Field(default=None)
    """
    Curve identifier. Always `P-256`.
    """

    x: typing.Optional[str] = pydantic.Field(default=None)
    """
    The x coordinate of the EC public key, base64url-encoded (32 bytes, unpadded).
    """

    y: typing.Optional[str] = pydantic.Field(default=None)
    """
    The y coordinate of the EC public key, base64url-encoded (32 bytes, unpadded).
    """

    use: typing.Optional[str] = pydantic.Field(default=None)
    """
    Intended use of the key. `sig` indicates signature verification.
    """

    kid: typing.Optional[str] = pydantic.Field(default=None)
    """
    Key id that uniquely identifies this key, so clients can cache it and reload when it rotates.
    """

    alg: typing.Optional[str] = pydantic.Field(default=None)
    """
    Signing algorithm. `ES256` is ECDSA using P-256 and SHA-256.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
