# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class LogEntry(UniversalBaseModel):
    """
    A single API call as recorded after the request completed.
    """

    timestamp: str = pydantic.Field()
    """
    When the API call completed (ISO-8601 UTC).
    """

    method: str = pydantic.Field()
    """
    HTTP method of the request.
    """

    resource: str = pydantic.Field()
    """
    Top-level resource the call targeted, derived from the request path — for example `documents`, `records`, `search`, `schemas`, `folders`, `entities`, `namespaces`, `users`, `usage`, `auth`, `models`, `ping`, `rag`, `chat`, `ask`, `erasure-requests`, or `export`. Rows may also carry values that are not filterable via the `resource` query parameter, and `clients`/`orgs` appear on rows written before those identity surfaces were folded into `entities`.
    """

    context_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contextId"),
        pydantic.Field(
            alias="contextId",
            description="The app context the request operated under — the context partition the credential carried. `*` for a root/cross-context caller. Null for older log lines or for entry points that are not context-scoped.",
        ),
    ] = None
    status: int = pydantic.Field()
    """
    HTTP response status code.
    """

    key_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="keyId"),
        pydantic.Field(
            alias="keyId",
            description="ID of the API key or scoped token that issued the request. Null if the request was unauthenticated (extremely rare — most paths require auth before logging).",
        ),
    ] = None
    duration_ms: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="durationMs"),
        pydantic.Field(
            alias="durationMs", description="Total request duration in milliseconds, from auth to response completion."
        ),
    ] = None
    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full request path.
    """

    request_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="requestId"),
        pydantic.Field(
            alias="requestId",
            description="Correlation id for this call. Quote it when contacting support so the call can be traced. Most useful on failures, but recorded for successful calls too. Where an error response body carries a `requestId`, it is this same id.",
        ),
    ] = None
    error_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="errorCode"),
        pydantic.Field(
            alias="errorCode",
            description="Error code explaining WHY a failed call was rejected, when the failure had a typed code — an uppercase token such as `RATE_LIMITED`, `SCRIPT_ERROR` or `VERSION_CONFLICT`. **This set is open and grows as the platform gains new typed failures, so treat these as examples rather than an exhaustive list**: branch on the specific codes your integration handles and fall back to generic handling for anything else, rather than matching against a fixed set. The codes a given call can return are documented on that endpoint's own error responses; a script execution additionally reports the name of its failure category, the same vocabulary `GET /v1/trigger-failures` returns in `category`. Null for successful calls, for failures that carry only a message, and for calls recorded before this release that are still within your log retention window. Request and response bodies are never logged, so no further detail is available here by design.",
        ),
    ] = None
    delegation_chain: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="delegationChain"),
        pydantic.Field(
            alias="delegationChain",
            description="A JSON-encoded record of who delegated the credential that made this call, present only when the request was made under a key minted via the `delegate-mint` capability (see `POST /v1/admin/keys/scoped`). Null for the overwhelming majority of calls, which carry no delegation.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
