# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class LogEntry(UniversalBaseModel):
    """
    A single API call as recorded after the request completed.
    """

    timestamp: str = pydantic.Field()
    """
    When the API call completed (ISO-8601 UTC).
    """

    method: str = pydantic.Field()
    """
    HTTP method of the request.
    """

    resource: str = pydantic.Field()
    """
    Top-level resource the call targeted (one of `documents`, `records`, `search`, `schemas`, `folders`, `clients`, `orgs`, `users`, `usage`, `auth`, `models`, `ping`, `rag`, `chat`, `ask`, `erasure-requests`, or `export`), derived from the request path.
    """

    context_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contextId"),
        pydantic.Field(
            alias="contextId",
            description="The app context the request operated under — the context partition the credential carried. `*` for a root/cross-context caller. Null for older log lines or for entry points that are not context-scoped.",
        ),
    ] = None
    status: int = pydantic.Field()
    """
    HTTP response status code.
    """

    key_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="keyId"),
        pydantic.Field(
            alias="keyId",
            description="ID of the API key or scoped token that issued the request. Null if the request was unauthenticated (extremely rare — most paths require auth before logging).",
        ),
    ] = None
    duration_ms: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="durationMs"),
        pydantic.Field(
            alias="durationMs", description="Total request duration in milliseconds, from auth to response completion."
        ),
    ] = None
    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full request path.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
