# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MintTokenResponse(UniversalBaseModel):
    """
    A minted scoped token and its absolute expiration. The token is an opaque string for use in `Authorization: Bearer <token>` headers; `expiresAt` mirrors the token's `exp` claim (seconds since the Unix epoch) so you can decide when to refresh without decoding the token.
    """

    token: str = pydantic.Field()
    """
    The opaque bearer token. Send it as `Authorization: Bearer <token>` on subsequent requests.
    """

    expires_at: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(
            alias="expiresAt",
            description="When the token expires, as seconds since the Unix epoch (matches the token's `exp` claim).",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
