# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .model_data_version_response import ModelDataVersionResponse


class ModelDataVersionPage(UniversalBaseModel):
    """
    A single page of version-history entries, returned by the `.../versions` endpoints. The `data` array holds the entries. `nextCursor` is an opaque cursor you pass to fetch the next page; it is null when no more pages remain.
    """

    data: typing.Optional[typing.List[ModelDataVersionResponse]] = pydantic.Field(default=None)
    """
    The items on this page, in the endpoint's natural order. Empty when there are no results.
    """

    next_cursor: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="nextCursor"),
        pydantic.Field(
            alias="nextCursor",
            description="An opaque cursor for the next page. Pass it back as the `startFrom` query parameter to continue paging; null when there are no more results. Treat it as opaque — do not parse or construct it.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
