# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class OrgResponse(UniversalBaseModel):
    """
    An organization in your account — an organizational unit you define and control.
    """

    created: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this call created a new organization. True when a new organization was created; false when an organization with the same `externalId` already existed and was returned unchanged (idempotent create) or updated (when `?upsert=true`). Present only on the create response (POST /v1/orgs); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing organization was returned.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Vectros-assigned ID (UUID) for this organization. Use it wherever you reference the organization elsewhere — for example as the owner of a record or as a filter value when listing records.
    """

    external_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalId"),
        pydantic.Field(
            alias="externalId",
            description="Your own identifier for this organization, as supplied when it was created.",
        ),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable name of the organization.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Lifecycle status of the organization: `ACTIVE` (usable normally) or `SUSPENDED` (retained but blocked from new operations).
    """

    payload: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Free-form key-value attributes stored with the organization.
    """

    schema_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="schemaId"),
        pydantic.Field(
            alias="schemaId",
            description="ID of the record schema that governs payload validation and lookup indexing for this organization, or null if the organization is not bound to a schema.",
        ),
    ] = None
    schema_version: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="schemaVersion"),
        pydantic.Field(
            alias="schemaVersion",
            description="The version of the governing schema in effect when this organization was last written. The organization keeps the schema version it was stamped with even after the schema is later edited. Null when the organization is not bound to a schema.",
        ),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="Timestamp when the organization was created, as an ISO-8601 UTC timestamp."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
