# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .content_delta_event_event import ContentDeltaEventEvent
from .done_event_event import DoneEventEvent
from .error_event_event import ErrorEventEvent
from .rag_search_result import RagSearchResult
from .search_results_event_event import SearchResultsEventEvent
from .truncation_warning_event_event import TruncationWarningEventEvent
from .truncation_warning_event_reason import TruncationWarningEventReason


class RagStreamEvent_SearchResults(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/rag`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["search_results"] = "search_results"
    event: SearchResultsEventEvent
    results: typing.List[RagSearchResult]
    total_results: typing_extensions.Annotated[
        int, FieldMetadata(alias="totalResults"), pydantic.Field(alias="totalResults")
    ]
    search_time_ms: typing_extensions.Annotated[
        int, FieldMetadata(alias="searchTimeMs"), pydantic.Field(alias="searchTimeMs")
    ]
    degraded: typing.Optional[bool] = None
    degraded_legs: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="degradedLegs"), pydantic.Field(alias="degradedLegs")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RagStreamEvent_TruncationWarning(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/rag`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["truncation_warning"] = "truncation_warning"
    event: TruncationWarningEventEvent
    results_requested: typing_extensions.Annotated[
        int, FieldMetadata(alias="resultsRequested"), pydantic.Field(alias="resultsRequested")
    ]
    results_used: typing_extensions.Annotated[
        int, FieldMetadata(alias="resultsUsed"), pydantic.Field(alias="resultsUsed")
    ]
    reason: TruncationWarningEventReason

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RagStreamEvent_ContentDelta(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/rag`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["content_delta"] = "content_delta"
    event: ContentDeltaEventEvent
    delta: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RagStreamEvent_Done(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/rag`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["done"] = "done"
    event: DoneEventEvent
    input_tokens: typing_extensions.Annotated[
        int, FieldMetadata(alias="inputTokens"), pydantic.Field(alias="inputTokens")
    ]
    output_tokens: typing_extensions.Annotated[
        int, FieldMetadata(alias="outputTokens"), pydantic.Field(alias="outputTokens")
    ]
    model: str
    platform_credits_charged: typing_extensions.Annotated[
        float, FieldMetadata(alias="platformCreditsCharged"), pydantic.Field(alias="platformCreditsCharged")
    ]
    inference_balance_cents_charged: typing_extensions.Annotated[
        int, FieldMetadata(alias="inferenceBalanceCentsCharged"), pydantic.Field(alias="inferenceBalanceCentsCharged")
    ]
    cache_read_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="cacheReadTokens"), pydantic.Field(alias="cacheReadTokens")
    ] = None
    cache_create_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="cacheCreateTokens"), pydantic.Field(alias="cacheCreateTokens")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RagStreamEvent_Error(UniversalBaseModel):
    """
    A single Server-Sent Event from `POST /v1/rag`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
    """

    type: typing.Literal["error"] = "error"
    event: ErrorEventEvent
    message: str
    code: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


RagStreamEvent = typing_extensions.Annotated[
    typing.Union[
        RagStreamEvent_SearchResults,
        RagStreamEvent_TruncationWarning,
        RagStreamEvent_ContentDelta,
        RagStreamEvent_Done,
        RagStreamEvent_Error,
    ],
    pydantic.Field(discriminator="type"),
]
