# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .filter_value import FilterValue
from .rag_search_content_types_item import RagSearchContentTypesItem
from .rag_search_mode import RagSearchMode


class RagSearch(UniversalBaseModel):
    """
    Configuration for the retrieval step: search mode, result limit, filters, and ownership/folder scope.
    """

    mode: typing.Optional[RagSearchMode] = pydantic.Field(default=None)
    """
    Retrieval mode: `HYBRID` combines keyword and semantic search, `SEMANTIC` uses vector similarity only, `TEXT` uses keyword (BM25) matching only. Defaults to `HYBRID`.
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of results to retrieve before building the prompt. Defaults to 10; the maximum is 50.
    """

    filters: typing.Optional[typing.Dict[str, FilterValue]] = pydantic.Field(default=None)
    """
    Field filters to apply to your indexed content, as a map of field name to required value.
    """

    user_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="userId"),
        pydantic.Field(alias="userId", description="Restrict retrieval to content owned by this user id."),
    ] = None
    org_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="orgId"),
        pydantic.Field(alias="orgId", description="Restrict retrieval to content owned by this organization id."),
    ] = None
    client_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="clientId"),
        pydantic.Field(alias="clientId", description="Restrict retrieval to content tagged with this client id."),
    ] = None
    content_types: typing_extensions.Annotated[
        typing.Optional[typing.List[RagSearchContentTypesItem]],
        FieldMetadata(alias="contentTypes"),
        pydantic.Field(
            alias="contentTypes",
            description='Narrow retrieval to specific content types. When omitted, both documents and records are searched — records are valid grounding content too (for example, structured patient data or intake forms). Pass ["documents"] for documents only or ["records"] for records only. Each retrieved result carries a `sourceType` field indicating which type it is.',
        ),
    ] = None
    folder_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="folderId"),
        pydantic.Field(
            alias="folderId",
            description="Restrict retrieval to content (documents or records) in this exact folder. Folders are a unified organizational primitive and may hold mixed content. Provide the UUID of a folder. To include a folder and all of its descendants instead, use `rootFolderId`.",
        ),
    ] = None
    root_folder_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="rootFolderId"),
        pydantic.Field(
            alias="rootFolderId",
            description="Restrict retrieval to content under this subtree — the folder and all of its descendants. Provide the UUID of a top-level (root) folder. Applies uniformly to documents and records. Use `folderId` to scope to a single folder exactly.",
        ),
    ] = None
    type_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="typeName"),
        pydantic.Field(
            alias="typeName",
            description="Restrict retrieval to content of a specific schema type — for example `patient` or `runbook`. Applies to both documents and records: any item whose bound schema type matches is kept. On its own it narrows both content types to that type; combine it with `contentTypes` to narrow within a single content type. Untyped content (ingested without a schema) never matches.",
        ),
    ] = None
    created_after: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAfter"),
        pydantic.Field(
            alias="createdAfter",
            description="Restrict retrieval to content created at or after this ISO-8601 UTC timestamp. Useful for incremental retrieval (for example, answering based only on content ingested today). Pair with `createdBefore` to define a time window.",
        ),
    ] = None
    created_before: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdBefore"),
        pydantic.Field(
            alias="createdBefore",
            description="Restrict retrieval to content created at or before this ISO-8601 UTC timestamp. Pair with `createdAfter` to define a time window, or use alone to scope retrieval to content older than a cutoff.",
        ),
    ] = None
    require_complete: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="requireComplete"),
        pydantic.Field(
            alias="requireComplete",
            description="Require complete retrieval. When true, if a search backend is unavailable the request returns HTTP 503 before any answer is streamed, rather than grounding the answer on partial results. Defaults to false, in which case an outage degrades to the surviving search engine and the `search_results` event reports `degraded: true`. Set this to true when an answer grounded on incomplete retrieval is unacceptable.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
