# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .scope_clause import ScopeClause


class RoleResponse(UniversalBaseModel):
    """
    A role: a named, reusable set of scope clauses that can be assigned to users independently of any one identity.
    """

    created: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this call created a new role. True when a new role was created; false when a role with the same `roleId` already existed and was returned unchanged (idempotent create) or updated (when `?upsert=true`). Present only on the create response (POST /v1/app-contexts/{contextId}/roles); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing role was returned.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The role's globally unique identifier, composed from your account, the app context, and the role ID. Pass this value as the pagination cursor to fetch the next page.
    """

    context_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contextId"),
        pydantic.Field(alias="contextId", description="The ID of the app context this role belongs to."),
    ] = None
    role_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="roleId"),
        pydantic.Field(alias="roleId", description="Your own identifier for this role within the app context."),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    A human-readable display name for the role.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional free-text description of what the role grants.
    """

    scopes: typing.Optional[typing.List[ScopeClause]] = pydantic.Field(default=None)
    """
    The role's permissions, expressed as one or more scope clauses. An action is permitted if any clause allows it and that clause's data scope matches the target.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the role was created, as an ISO-8601 UTC timestamp."),
    ] = None
    last_modified: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastModified"),
        pydantic.Field(
            alias="lastModified", description="When the role was last modified, as an ISO-8601 UTC timestamp."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
