# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ScriptRequest(UniversalBaseModel):
    """
    Request body for pushing a new script object version. Scripts are immutable per version — there is no update surface; push a new version with another POST.
    """

    name: str = pydantic.Field()
    """
    The script's referenceable name/slug — stable across versions. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Required.
    """

    source: str = pydantic.Field()
    """
    The script's source text, stored as-is: nothing parses or validates it at push time, so a syntax error surfaces as a `SCRIPT_ERROR` when the version first runs — from a trigger rule that references it, or from `POST /v1/scripts/execute`. Required, non-blank. Capped at 300,000 UTF-8 bytes (~300 KB) — an oversized push is rejected with a 400.
    """

    declared_input_contract: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="declaredInputContract"),
        pydantic.Field(
            alias="declaredInputContract",
            description="Optional free-text description of the input shape this script expects. Not validated or enforced in this release. Capped at 50,000 UTF-8 bytes (~50 KB) — an oversized value is rejected with a 400.",
        ),
    ] = None
    provisioned_by: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="provisionedBy"),
        pydantic.Field(
            alias="provisionedBy",
            description="An optional provenance marker naming the blueprint that provisions this script, so a convergent caller can tell a script it manages from one hand-authored or owned by a different blueprint. Not currently sent by `vectros bootstrap --blueprint`, which does not yet set this field for scripts. Leave it unset for a script you manage yourself. MAY BE SET ON ABSENT, NEVER CHANGED, evaluated against the CURRENT LATEST version of this `name` at push time: if the latest version has no marker recorded, this push may set any value (including onto a previously-unmarked, hand-authored name); if the latest version already has one recorded, an omitted value inherits it forward, and supplying a DIFFERENT value is refused. This compares against whichever version is newest right now, not a value fixed for the name's whole history — deleting the version(s) carrying a given marker and pushing again is unconstrained by it.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
