# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .storage_entry import StorageEntry


class StorageBytesSearch(UniversalBaseModel):
    """
    Search index storage bytes and estimated credits by index type
    """

    text: typing.Optional[StorageEntry] = None
    semantic: typing.Optional[StorageEntry] = None
    hybrid: typing.Optional[StorageEntry] = None
    parent_chunks: typing_extensions.Annotated[
        typing.Optional[StorageEntry], FieldMetadata(alias="parentChunks"), pydantic.Field(alias="parentChunks")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
