# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tenant_detail import TenantDetail


class Tenants(UniversalBaseModel):
    """
    Usage breakdown by environment (your live and test environments). Your account totals at the top of the response equal the sum of live + test for each metric.
    """

    live: typing.Optional[TenantDetail] = None
    test: typing.Optional[TenantDetail] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
